### PR TITLE
fix(clip): add an extra space to the clip-path width to prevent unexpected clip. close #19051

### LINKED ISSUE #19051: [Bug] Series-line is clipped incorrectly at the rightmost position
### Version

5.4.3

### Link to Minimal Reproduction

https://codepen.io/rexskz/pen/WNLweyw

### Steps to Reproduce

1. Open the codepen link.
2. Look at the rightmost position of the line.

### Current Behavior

It's clipped incorrectly, but the leftmost position of the line is okay.

image

### Expected Behavior

The rightmost position should not be clipped, just like the leftmost one.

### Environment

```markdown
- OS: macOS Ventura
- Browser: Chrome 116.0.5845.110
- Framework: /
```

### Any additional comments?

The root cause is that ECharts uses `Math.round` in `createClipPathFromCoordSys.ts`:

```ts
const rect = cartesian.getArea();
let width = rect.width;
width = Math.round(width);
```

The `width` here can be a float with the decimal part less than 0.5:

image

Finally, it results in the incorrect `clipPath`, just 1px smaller than expected:

image

---

This issue can only be reproduced in a container with a specific width (`503px` in the codepen link).

This issue might be related to #11369; considering it meant to extend the clipPath and use `Math.floor` on `x`, I think it's okay to use `Math.ceil` on `width` to ensure the clipPath is large enough to contain the whole line (with cap).

### PR DESCRIPTION
**Pull request by RexSkz**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Add an extra space to the clip-path `width`. This will prevent the unexpected clip.

### Fixed issues

- #19051

### Before: What was the problem?

As the example https://codepen.io/rexskz/pen/WNLweyw shows, the rightmost position of the line that has `cap: 'round'` is clipped incorrectly, while the leftmost part is okay.

image

This issue only happens on the device with `devicePixelRatio >= 3`, and the chart canvas must have a special width.

### After: How does it behave after the fixing?

The rightmost position of the line should not be clipped.

image

This is caused by a round-off error.

Let's see if the rect is:

```js
x = 80.8;      // float
y = 100;
width = 500.4; // float
height = 100;
// x + width = 581.2
```

Browsers will render the clip-path using `rect` but handle the value as integers, so the original code converts `x` and `width` to integers:

```js
x = Math.floor(x);         // 80
width = Math.round(width); // 500
// x + width = 580
```

The result is 1.2 less, meaning the graph's rightmost `1.2px` will be clipped.

To make sure the clip-path wraps the whole graph, the `x` should keep floored, but the `width` should be ceiled (not rounded), and if `x` is floored, `width` should be add an extra `1px`.

P.S. During the visual test, I found that some cases may also be clipped incorrectly before, and will be corrected in this PR, for example:

image

image

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/chart/helper/createClipPathFromCoordSys.ts [hunk 1]
```diff
@@ -43,7 +44,14 @@ function createGridClipPath(
     let width = rect.width;
     let height = rect.height;
 
-    const lineWidth = seriesModel.get(['lineStyle', 'width']) || 2;
+    const zr = cartesian.model.ecModel.scheduler.ecInstance.getZr();
+    const dpr = zr.painter instanceof CanvasPainter
```
Comment (Ovilia) [inline src/chart/helper/createClipPathFromCoordSys.ts:48]: A better way to get dpr is from https://github.com/apache/echarts/blob/master/src/core/echarts.ts#L703 . You may add a new parameter to this function like `dpr`.

File: src/chart/helper/createClipPathFromCoordSys.ts [hunk 2]
```diff
@@ -43,7 +44,14 @@ function createGridClipPath(
...
+        ? zr.painter.dpr
+        : window.devicePixelRatio; /* global window */
+
+    const _lineWidth = seriesModel.get(['lineStyle', 'width']) || 2;
+    const lineWidth = _lineWidth * (dpr || 1);
```
Comment (Ovilia) [inline src/chart/helper/createClipPathFromCoordSys.ts:53]: Better with `const lineWidth = (seriesModel.get(['lineStyle', 'width']) || 2) * (dpr || 1);`

**Review by Ovilia — CHANGES_REQUESTED** [review]

File: src/chart/helper/createClipPathFromCoordSys.ts (hunk 1 above)
Comment (RexSkz) [reply src/chart/helper/createClipPathFromCoordSys.ts:48]: Oh yes, it's better, I'll change it soon.

**Comment by RexSkz** [comment]
@Ovilia Done; please take a look and notify me if there are other suggestions :)

**Comment by RexSkz** [comment]
How about triggering the workflow? I'll quickly fix the raised issue if there is one :)

**Comment by RexSkz** [comment]
It looks good :)

image

https://echarts.apache.org/examples/en/editor.html?version=PR-19056%405491cb3&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdPqVgAjYJaFcA4oxBEAZowA2eFR2sAC-weQ4-ESo9hTUdABu_kq0JGEkgUZUhLCi_MT2gsJiAIwArAAMPLAATADMVbU1ACzVNSUAHNUldWXdzQDs3ZW2-ehxNLJ-ENDKwfZ42sAA7ibkALZOfj7-gfOk07MmFH6TMYXoyxACYNpEfWOkTF6yHM7Qmvvo6fY_sKMhADcQA

**Comment by Ovilia** [comment]
Hi, I checked the demo with [5.4.3](https://echarts.apache.org/examples/en/editor.html?version=5.4.3&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdPqVgAjYJaFcA4oxBEAZowA2eFR2sAC-weQ4-ESo9hTUdABu_kq0JGEkgUZUhLCi_MT2gsJiAIwArAAMPLAATADMVbU1ACzVNSUAHNUldWXdzQDs3ZW2-ehxNLJ-ENDKwfZ42sAA7ibkALZOfj7-gfOk07MmFH6TMYXoyxACYNpElfv2TF6yHM7Qmo-h--nooyEAbiAA) and it seems not to be clipped. Did I miss anything here?

**Comment by RexSkz** [comment]
> Hi, I checked the demo with [5.4.3](https://echarts.apache.org/examples/en/editor.html?version=5.4.3&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdPqVgAjYJaFcA4oxBEAZowA2eFR2sAC-weQ4-ESo9hTUdABu_kq0JGEkgUZUhLCi_MT2gsJiAIwArAAMPLAATADMVbU1ACzVNSUAHNUldWXdzQDs3ZW2-ehxNLJ-ENDKwfZ42sAA7ibkALZOfj7-gfOk07MmFH6TMYXoyxACYNpElfv2TF6yHM7Qmo-h--nooyEAbiAA) and it seems not to be clipped. Did I miss anything here?

Slightly resize the page to a specific width (e.g. `1346px` ~ `1348px` in my Mac) and you'll see the clipping issue at the right:

image

The correct behaviour should be:

image

**Comment by RexSkz** [comment]
Oh, it seems that using `Math.ceil` is enough, no need to consider DPR... (The line width is `50px` but the error is `1px`, it must be a round-off error only.)

I'll change my code and see if it works well.

**Comment by RexSkz** [comment]
Hi @Ovilia, I've made changes to my code. Please have a look, it should be a lot simpler than the previous version~

**Review by Ovilia — APPROVED** [review]
Thanks for your contribution. Please don't use force push in your next PR because we'd like to record every commit changes. Don't worry if there are too many commits. The reviewer will use squash push when necessary.
