### PR TITLE
fix(candlestick): fix candlestick render error with `series.encode`

### LINKED ISSUE #21322: [Bug] on horizontal candlestick
### Version

6.0.0

### Link to Minimal Reproduction

[Example](https://echarts.apache.org/examples/en/editor.html?helgasoft=candlestick&code=CYQwbiA2AEC80G0BQ1oG9oUgVwKYC5EByAJgAYBGAdgFoKyaSAWIgGmnPYGYn37uAHAF1oAX1Yp0mKHkIJSlWvUYBWNtCZluK7lugqyI8ZIxZZxctToMSANnVcKg7l3ZMmRialMyCFxdaMVA4CfDr6biRGSEIA3EigAE4gAJ5wiJLylko2LOyc0Dx8elzCXv5WyiRqbiXhXHoGQuVZAVX23E6FoYWuGh4tCpU2wc7QFOHhTFEx8QD2AA4ALgCWcwB26WiSAB4AgjsrAM6EGEspC35EqwC2uERi7CkHx6eoxqhHuIkruCcZqG80HOl0IRAAxiB1sBIH9VuCANZsSSA6C4dbgubAPwYHaEPQpORdPokNyeVAAegp0DmCJRgNASxAhFAWHKqKpjOZ0CSqQ51KOIDu0ESf2wkCWFIARtgAOb00SSIRIUTzZZrTbwbaofaHf4YR7QZ56t4gq63e6PSRfH5_OT0s4XK6Q6Gwo7wpHswHozHYt6E6B6PGIYn5MmG6BU6AAOXFMAACnMVuslt9oABRHbg3DqjbQAAU0fj6YAlPTUFyWeAoAqlSrYkA)

### Steps to Reproduce

open Chrome DevTools to see error

### Current Behavior

[candlestick.encode](https://echarts.apache.org/en/option.html#series-candlestick.encode) allows multiple values to be associated with the X axis. Even the example is with `x: [3, 1, 5],`. This means the candlestick should be shown horizontally. 
Generates a Null Pointer Exception (NPE)  _TypeError: Cannot read properties of undefined (reading 'sign')_ on line
https://github.com/apache/echarts/blob/6b82c48a03e15964035f53d9012061e760f8d393/src/chart/candlestick/candlestickVisual.ts#L68

### Expected Behavior

horizontal candlesticks

### Environment

```markdown
- OS:
- Browser: Chrome
- Framework: JS
```

### Any additional comments?

probably very low priority, but still a bug to be reported

### PR DESCRIPTION
**Pull request by PPRAMANIK62**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Fixes TypeError: Cannot read properties of undefined (reading 'sign') and displays horizontal candlesticks properly

### Fixed issues

- Fix #21322

### Before: What was the problem?

Screenshot_20-Oct_19-45-20_18405

### After: How does it behave after the fixing?

Screenshot_20-Oct_19-43-42_30857

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/chart/candlestick/CandlestickView.ts [hunk 1]
```diff
@@ -110,6 +110,9 @@ class CandlestickView extends ChartView {
             .add(function (newIdx) {
                 if (data.hasValue(newIdx)) {
                     const itemLayout = data.getItemLayout(newIdx) as CandlestickItemLayout;
+                    if (!itemLayout) {
```
Comment (plainheart) [inline src/chart/candlestick/CandlestickView.ts]: If everything goes well, `itemLayout` should never be null. If we simply ignore it, potential errors might be hidden unexpectedly. I suggest not adding this non-null check.

File: src/chart/helper/whiskerBoxCommon.ts [hunk 2]
```diff
@@ -76,10 +76,37 @@ class WhiskerBoxCommonMixin<Opts extends CommonOption> {
...
+            else if (yAxisType === 'category') {
+                option.layout = 'vertical';
+                ordinalMeta = yAxisModel.getOrdinalMeta();
+                addOrdinal = !this._hasEncodeRule('y');
+            }
+            else {
+                option.layout = option.layout || 'horizontal';
+            }
+        }
+        else if (xAxisType === 'category') {
```
Comment (plainheart) [inline src/chart/helper/whiskerBoxCommon.ts]: Maybe adding simple support for the time axis is enough?

```javascript
// ...
}
else if (xAxisType === 'time') {
    option.layout = 'horizontal';
}
else if (yAxisType === 'time') {
    option.layout = 'vertical';
}
```

File: src/chart/candlestick/CandlestickView.ts (hunk 1 above)
Comment (PPRAMANIK62) [reply src/chart/candlestick/CandlestickView.ts]: Sounds good, will remove those checks.

File: src/chart/helper/whiskerBoxCommon.ts (hunk 2 above)
Comment (PPRAMANIK62) [reply src/chart/helper/whiskerBoxCommon.ts]: Thanks for this, it's actually a better solution.

File: test/candlestick-horizontal.html [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+                        type: "time",
+                    },
+                    series: [
+                        {
+                            type: "candlestick",
+                            encode: {
+                                x: [1, 3, 2, 4],
+                                y: 0,
+                            },
+                            data: daval,
```
Comment (plainheart) [inline test/candlestick-horizontal.html]: Please add more cases to test the behavior when:

- xAxis is time
- xAxis is category
- yAxis is time
- yAxis is category
- encode 0 as y
- encode 0 as x
- data uses `daval`
- data uses `datay`

And it would be better if you also test if this change works for #20319 (include boxplot on time axis) as well.

File: src/chart/candlestick/candlestickVisual.ts [hunk 4]
```diff
@@ -65,7 +65,11 @@ const candlestickVisual: StageHandler = {
                 let dataIndex;
                 while ((dataIndex = params.next()) != null) {
                     const itemModel = data.getItemModel(dataIndex);
-                    const sign = data.getItemLayout(dataIndex).sign;
```
Comment (plainheart) [inline src/chart/candlestick/candlestickVisual.ts:68]: This non-null check can be removed as well.

File: src/chart/helper/whiskerBoxCommon.ts [hunk 5]
```diff
@@ -17,17 +17,17 @@
...
 import type Axis2D from '../../coord/cartesian/Axis2D';
+import type CartesianAxisModel from '../../coord/cartesian/AxisModel';
 import { CoordDimensionDefinition } from '../../data/helper/createDimensions';
+import { getDimensionTypeByAxis } from '../../data/helper/dimensionHelper';
+import { makeSeriesEncodeForAxisCoordSys } from '../../data/helper/sourceHelper';
+import type SeriesData from '../../data/SeriesData';
+import type GlobalModel from '../../model/Global';
+import type SeriesModel from '../../model/Series';
+import type { LayoutOrient, SeriesOnCartesianOptionMixin, SeriesOption } from '../../util/types';
+import createSeriesDataSimply from './createSeriesDataSimply';
```
Comment (plainheart) [inline src/chart/helper/whiskerBoxCommon.ts]: These changes seem unrelated to this bug. I suggest recovering them, including Line 175.

**Review by plainheart — CHANGES_REQUESTED** [review]

File: src/chart/helper/whiskerBoxCommon.ts (hunk 5 above)
Comment (PPRAMANIK62) [reply src/chart/helper/whiskerBoxCommon.ts]: Sorry for these, will be more careful while committing changes

File: src/chart/candlestick/candlestickVisual.ts (hunk 4 above)
Comment (PPRAMANIK62) [reply src/chart/candlestick/candlestickVisual.ts:68]: Removed.

File: test/candlestick-horizontal.html (hunk 3 above)
Comment (PPRAMANIK62) [reply test/candlestick-horizontal.html]: I've added more test cases covering the mentioned. 
Also boxplot tests are working (encoding rules are respected)
image
image
image
image
image
