### PR TITLE
fix(line): normalize the infinite value when calculating the visual gradient.

### LINKED ISSUE #15407: 当x轴为时间轴时，visualMap展示的颜色不对
### Version
5.1.2

### Steps to reproduce
x轴设为时间轴，visualMap设置pieces和outOfRange，series的data的值都在pieces的范围之外，线条颜色显示不正确

### What is expected?
线条显示灰色

### What is actually happening?
线条显示红色

```js
{
        title: {
            text: 'Beijing AQI',
            left: '1%'
        },
        tooltip: {
            trigger: 'axis'
        },
        grid: {
            left: '5%',
            right: '15%',
            bottom: '10%'
        },
        xAxis: {
            "type": "time",
            "boundaryGap": true,
        },
        yAxis: {},
        toolbox: {
            right: 10,
            feature: {
                dataZoom: {
                    yAxisIndex: 'none'
                },
                restore: {},
                saveAsImage: {}
            }
        },
        dataZoom: [{
            startValue: '2014-06-01'
        }, {
            type: 'inside'
        }],
        visualMap: {
            top: 50,
            right: 10,
            pieces: [
              {
                "gte": 300,
                "lt": 400,
                "color": "#FF2E00"
              },
              {
                "gte": 400,
                "color": "#D00000"
              }
            ],
            outOfRange: {
                color: '#999'
            }
        },
        series: {
            name: 'Beijing AQI',
            type: 'line',
            data: [
        {
          "name": "474eb6f5",
          "value": [
            1626943980000,
            128
          ]
        },
        {
          "name": "474eb6f5",
          "value": [
            1626944040000,
            186
          ]
        },
        {
          "name": "474eb6f5",
          "value": [
            1626944100000,
            262
          ]
        },
        {
          "name": "474eb6f5",
          "value": [
            1626944160000,
            231
          ]
        },
        {
          "name": "474eb6f5",
          "value": [
            1626944220000,
            65
          ]
        },
        {
          "name": "474eb6f5",
          "value": [
            1626944280000,
            227
          ]
        },
        {
          "name": "474eb6f5",
          "value": [
            1626944340000,
            31
          ]
        },
        {
          "name": "474eb6f5",
          "value": [
            1626944400000,
            241
          ]
        },
        {
          "name": "474eb6f5",
          "value": [
            1626944460000,
            103
          ]
        },
        {
          "name": "474eb6f5",
          "value": [
            1626944520000,
            172
          ]
        },
        {
          "name": "474eb6f5",
          "value": [
            1626944580000,
            241
          ]
        },
        {
          "name": "474eb6f5",
          "value": [
            1626944640000,
            222
          ]
        }],
        }
    }
```

### PR DESCRIPTION
**Pull request by plainheart**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Resolves #15407. When `visualMap` is enabled, the line color is unexpected.

### Fixed issues

- #15407

### After: How is it fixed in this PR?

Revert the change brought by #14602 in `LineView.ts` and normalize the infinite value

https://github.com/apache/echarts/blob/cf7c4efc5c33961e1e932c450e2c16073feaa8fc/src/chart/line/LineView.ts#L246

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

Please refer to `test/linear-gradient.html`.

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/chart/line/LineView.ts [hunk 1]
```diff
@@ -233,17 +238,17 @@ function getVisualGradient(
...
-    interface ColorStop {
-        offset: number
-        coord?: number
-        color: ColorString
-    }
     // dataToCoord mapping may not be linear, but must be monotonic.
     const colorStops: ColorStop[] = zrUtil.map(visualMeta.stops, function (stop) {
+        let coord = axis.toGlobalCoord(axis.dataToCoord(stop.value));
+        // normalize the infinite value
+        isNaN(coord) || isFinite(coord)
```
Comment (pissang) [inline src/chart/line/LineView.ts:247]: We knew Infinite coord is calculated from an infinite value. So can we simplify the code to only clamp the infinite value.

```ts
const value = stop.value;
const coord = axis.toGlobalCoord(axis.dataToCoord(
  value, !(isFinite(value) || isNaN(value))
));
```

Comment (plainheart) [reply src/chart/line/LineView.ts:247]: This is simple and can solve the visual map bug but it can't work for the first case that uses the log axis.

Comment (plainheart) [reply src/chart/line/LineView.ts:247]: Take the first log axis case, it should be caused by `dataToCoord` will probably return an infinite value.

After invoking https://github.com/apache/echarts/blob/4db2f1e7c1eb50cf9305370aa85381e2840623ef/src/coord/Axis.ts#L125
the data may become `Infinity` and we expect `clamp` is `true` but before this, the `clamp` was calculated as `false`.

So it may be better to check again and clamp after the first coordinate conversion.

Now the logic should be like this,

```ts
const value = stop.value || 0;
let coord = axis.toGlobalCoord(axis.dataToCoord(value, !isFinite(value)));
// if coord is still infinite
isNaN(coord) || isFinite(coord) || (coord = axis.toGlobalCoord(axis.dataToCoord(coord, true)));
```

Comment (plainheart) [reply src/chart/line/LineView.ts:247]: Take the first log axis case, it should be because `dataToCoord` will probably return an infinite value.

After invoking https://github.com/apache/echarts/blob/4db2f1e7c1eb50cf9305370aa85381e2840623ef/src/coord/Axis.ts#L125
the data may become `Infinity`.
We expect `clamp` is `true` but before this, `clamp` was calculated as `false`.

So it may be better to check again and clamp after the first coordinate conversion
or modify the `dataToCoord` function (I'm afraid we can't)

Comment (pissang) [reply src/chart/line/LineView.ts:247]: Understand, thanks for the explaination

**Review by pissang — APPROVED** [review]
