### PR TITLE
fix: add symbolPath opacity. close #21074

### LINKED ISSUE #21074: [Bug]  blur.itemStyle.opactiy setting invalidates
### Version

5.6.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=radar&lang=ts

### Steps to Reproduce

option = {
  title: {
    text: 'Basic Radar Chart'
  },
  legend: {
    data: ['Allocated Budget', 'Actual Spending']
  },
  radar: {
    indicator: [
      { name: 'Sales', max: 6500 },
      { name: 'Administration', max: 16000 },
      { name: 'Information Technology', max: 30000 },
      { name: 'Customer Support', max: 38000 },
      { name: 'Development', max: 52000 },
      { name: 'Marketing', max: 25000 }
    ]
  },
  series: [
    {
      name: 'Budget vs spending',
      type: 'radar',
      data: [
        {
          value: [4200, 3000, 20000, 35000, 50000, 18000],
          name: 'Allocated Budget'
        },
        {
          value: [5000, 14000, 28000, 26000, 42000, 21000],
          name: 'Actual Spending'
        }
      ],
       emphasis: {
          focus: 'self',
          lineStyle: {
            width: 2,
          },
          itemStyle: {
            borderColor: null,
            borderWidth: 2,
            opacity: 1,
          },
        },
        blur: {
          lineStyle: {
            opacity: 0.3,
          },
          itemStyle: {
            opacity: 0.2,
            shadowBlur: 5,
          },
        },
    }
  ]
};

### Current Behavior

雷达图非选中维度的“点”没有和“线”一起透明度降低

### Expected Behavior

option = {
  title: {
    text: 'Basic Radar Chart'
  },
  legend: {
    data: ['Allocated Budget', 'Actual Spending']
  },
  radar: {
    indicator: [
      { name: 'Sales', max: 6500 },
      { name: 'Administration', max: 16000 },
      { name: 'Information Technology', max: 30000 },
      { name: 'Customer Support', max: 38000 },
      { name: 'Development', max: 52000 },
      { name: 'Marketing', max: 25000 }
    ]
  },
  series: [
    {
      name: 'Budget vs spending',
      type: 'radar',
      data: [
        {
          value: [4200, 3000, 20000, 35000, 50000, 18000],
          name: 'Allocated Budget'
        },
        {
          value: [5000, 14000, 28000, 26000, 42000, 21000],
          name: 'Actual Spending'
        }
      ],
       emphasis: {
          focus: 'self',
          lineStyle: {
            width: 2,
          },
          itemStyle: {
            borderColor: null,
            borderWidth: 2,
            opacity: 1,
          },
        },
        blur: {
          lineStyle: {
            opacity: 0.3,
          },
          itemStyle: {
            opacity: 0.2,
            shadowBlur: 5,
          },
        },
    }
  ]
};

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by mustcanbedo**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Review by Ovilia — CHANGES_REQUESTED** [review]
Why setting opacity to a fixed value? This bug should relates to `blur` state.

**Comment by mustcanbedo** [comment]
Referring to the transparency setting of the line, then do you need to design it here, I think the actual meaning of the bug proposer is that the transparency of the line and the point is not consistent&nbsp;


卤蛋?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wenli ***@***.***&gt;; 
发送时间: 2025年7月1日(星期二) 晚上6:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] fix: add symbolPath opacity. close #21074 (PR #21081)














 
@Ovilia requested changes on this pull request.
@Ovilia 请求对此拉取请求进行修改。
 
Why setting opacity to a fixed value? This bug should relates to blur state.
为何将透明度设为固定值？这个错误应该与 blur 状态有关。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
直接回复此邮件，在 GitHub 上查看，或取消订阅。
You are receiving this because you authored the thread.
您收到此邮件是因为您是此讨论串的作者。  Message ID: ***@***.***&gt;

**Comment by mustcanbedo** [comment]
Hello, I refer to the way you said.,Changed a version.,By the way, the original fixed way of the line was also deleted.

**Comment by mustcanbedo** [comment]
@Ovilia  Hello, it has been modified according to your comments and is waiting for your review

**Comment by mustcanbedo** [comment]
@Ovilia

**Review by Ovilia — CHANGES_REQUESTED** [review]
Sorry for the late reply. I think the overall direction is correct, and it can be simplified as [line series](https://github.com/apache/echarts/blob/master/src/chart/helper/Line.ts#L261-L263) does. And please add a test case in `radar.html` to test it.

**Comment by mustcanbedo** [comment]
@Ovilia  Hello, I learned how to write the line series again, changed the version, and added test cases to the radar.html

File: src/chart/radar/RadarView.ts [hunk 1]
```diff
@@ -177,92 +177,108 @@ class RadarView extends ChartView {
...
-
-            group.add(itemGroup);
-
-            polyline.useStyle(
-                zrUtil.defaults(
-                    itemModel.getModel('lineStyle').getLineStyle(),
-                    {
-                        fill: 'none',
-                        stroke: color
+            data.eachItemGraphicEl(function (itemGroup: graphic.Group, idx) {
```
Comment (Ovilia) [inline src/chart/radar/RadarView.ts]: Please don't change the indent if there's no problem with the old code. It makes the diff hard to review.

File: test/radar.html [hunk 2]
```diff
@@ -19,119 +18,144 @@
...
+            width: 100%;
+            height: 100%;
+        }
+    </style>
+    <div id="main"></div>
+    <script>
+
+        require([
+            'echarts'
+        ], function (echarts) {
```
Comment (Ovilia) [inline test/radar.html]: Again, please revert the changes of indent. If you are using auto-formatting tools, you may need to disable it.

**Review by Ovilia — CHANGES_REQUESTED** [review]
Please don't include `dist` in your PR.

File: test/radar.html (hunk 2 above)
Comment (mustcanbedo) [reply test/radar.html]: I'm sorry, I accidentally gave the PR to close when I withdrew the code, so I reopened a PR and submitted it again

**Comment by mustcanbedo** [comment]
@Ovilia  Hello, the issue of indentation has been changed

**Comment by mustcanbedo** [comment]
@Ovilia

File: src/chart/radar/RadarView.ts [hunk 3]
```diff
@@ -215,53 +215,84 @@ class RadarView extends ChartView {
 
             polygon.useStyle(
                 zrUtil.defaults(
-                    areaStyleModel.getAreaStyle(),
-                    {
-                        fill: color,
-                        opacity: 0.7,
-                        decal: itemStyle.decal
+                    itemModel.getModel('areaStyle').getAreaStyle(),
```
Comment (Ovilia) [inline src/chart/radar/RadarView.ts:226]: Any reason to use `itemModel.getModel('areaStyle').getAreaStyle()` instead of `areaStyleModel.getAreaStyle()`?

File: src/chart/radar/RadarView.ts [hunk 4]
```diff
@@ -215,53 +215,84 @@ class RadarView extends ChartView {
...
+                     {
```
Comment (Ovilia) [inline src/chart/radar/RadarView.ts]: Please fix the lint problems.

File: src/chart/radar/RadarView.ts [hunk 5]
```diff
@@ -215,53 +215,84 @@ class RadarView extends ChartView {
...
+            symbolGroup.eachChild((symbolPath: RadarSymbol) => {
                 if (symbolPath instanceof ZRImage) {
-                    const pathStyle = symbolPath.style;
-                    symbolPath.useStyle(zrUtil.extend({
-                        // TODO other properties like x, y ?
-                        image: pathStyle.image,
-                        x: pathStyle.x, y: pathStyle.y,
-                        width: pathStyle.width, height: pathStyle.height
-                    }, itemStyle));
+                  const ps = symbolPath.style
```
Comment (Ovilia) [inline src/chart/radar/RadarView.ts]: Don't change the indent.

File: src/chart/radar/RadarView.ts [hunk 6]
```diff
@@ -215,53 +215,84 @@ class RadarView extends ChartView {
...
+                        fill: color, 
+                        decal: itemStyle.decal 
                     }
                 )
             );
-            const emphasisModel = itemModel.getModel('emphasis');
-            const itemHoverStyle = emphasisModel.getModel('itemStyle').getItemStyle();
-            symbolGroup.eachChild(function (symbolPath: RadarSymbol) {
+            
+            symbolGroup.eachChild((symbolPath: RadarSymbol) => {
```
Comment (Ovilia) [inline src/chart/radar/RadarView.ts]: Don't make unnecessary changes. It makes it hard to review.

File: src/chart/radar/RadarView.ts [hunk 7]
```diff
@@ -215,53 +215,84 @@ class RadarView extends ChartView {
...
+                  labelFetcher: data.hostModel,
+                  labelDataIndex: idx,
+                  labelDimIndex: symbolPath.__dimIdx,
+                  defaultText: txt as string,
+                  inheritColor: color,
+                  defaultOpacity: itemStyle.opacity,
+                })
+            })
+        
+              function applyStateOpacity(state: 'emphasis' | 'select' | 'blur') {
```
Comment (Ovilia) [inline src/chart/radar/RadarView.ts]: `opacity` doesn't seem need to have special operation. This seems to be a wrong approach.

**Review by Ovilia — CHANGES_REQUESTED** [review]

File: src/chart/radar/RadarView.ts (hunk 3 above)
Comment (mustcanbedo) [reply src/chart/radar/RadarView.ts:226]: I wanted to adapt to the way polyline is written

File: src/chart/radar/RadarView.ts (hunk 7 above)
Comment (mustcanbedo) [reply src/chart/radar/RadarView.ts]: I'm sorry that maybe the name is a little inappropriate and makes you think it's a wrong function

File: src/chart/radar/RadarView.ts (hunk 6 above)
Comment (mustcanbedo) [reply src/chart/radar/RadarView.ts]: Hello, this morning is a pull of an old version, sorry

File: src/chart/radar/RadarView.ts (hunk 5 above)
Comment (mustcanbedo) [reply src/chart/radar/RadarView.ts]: Hello, this morning is a pull of an old version, sorry

File: src/chart/radar/RadarView.ts [hunk 8]
```diff
@@ -215,53 +215,79 @@ class RadarView extends ChartView {
 
             polygon.useStyle(
                 zrUtil.defaults(
-                    areaStyleModel.getAreaStyle(),
+                    itemModel.getModel('areaStyle').getAreaStyle(),
                     {
                         fill: color,
-                        opacity: 0.7,
```
Comment (Ovilia) [inline src/chart/radar/RadarView.ts:221]: This doesn't seem should be removed.

File: src/chart/radar/RadarView.ts [hunk 9]
```diff
@@ -215,53 +215,79 @@ class RadarView extends ChartView {
...
-                else {
-                    symbolPath.useStyle(itemStyle);
-                    symbolPath.setColor(color);
-                    symbolPath.style.strokeNoScale = true;
+                const emphasisModel = itemModel.getModel('emphasis')
+                const hoverStyle = emphasisModel.getModel('itemStyle').getItemStyle()
+                symbolPath.ensureState('emphasis').style = zrUtil.clone(hoverStyle)
+                let txt = data.getStore().get(data.getDimensionIndex(symbolPath.__dimIdx), idx)
+                if (txt == null || isNaN(txt as number)) {
+                  txt = ''
```
Comment (Ovilia) [inline src/chart/radar/RadarView.ts]: Please explain why these code changed from outside `if-else` into `else` clause?

File: src/chart/radar/RadarView.ts [hunk 10]
```diff
@@ -215,53 +215,79 @@ class RadarView extends ChartView {
```
Comment (Ovilia) [inline src/chart/radar/RadarView.ts:223]: Can we move the logic of `bindStateStyles` here in the loop of `zrUtil.each(['emphasis', 'select', 'blur'] `?

File: src/chart/radar/RadarView.ts [hunk 11]
```diff
@@ -215,53 +215,79 @@ class RadarView extends ChartView {
...
                     {
                         labelFetcher: data.hostModel,
                         labelDataIndex: idx,
                         labelDimIndex: symbolPath.__dimIdx,
-                        defaultText: defaultText as string,
-                        inheritColor: color as ColorString,
-                        defaultOpacity: itemStyle.opacity
+                        defaultText: txt as string,
+                        inheritColor: color,
+                        defaultOpacity: itemStyle.opacity,
```
Comment (Ovilia) [inline src/chart/radar/RadarView.ts]: Revert the changes if they are not related to this PR.

File: src/chart/radar/RadarView.ts (hunk 8 above)
Comment (mustcanbedo) [reply src/chart/radar/RadarView.ts:221]: Okay, if you expect to keep the original initialization line with opacity points

File: src/chart/radar/RadarView.ts (hunk 9 above)
Comment (mustcanbedo) [reply src/chart/radar/RadarView.ts]: Hello, I don't understand the meaning of this review

**Comment by mustcanbedo** [comment]
@Ovilia

File: src/chart/radar/RadarView.ts (hunk 3 above)
Comment (Ovilia) [reply src/chart/radar/RadarView.ts:226]: OK. This makes sense.

**Review by Ovilia — APPROVED** [review]

**Comment by Ovilia** [comment]
Thanks for your contribution!

**Comment by mustcanbedo** [comment]
Thank you for your review, I learned a lot, and I will continue to contribute in the future

**Comment by Ovilia** [comment]
> Thank you for your review, I learned a lot, and I will continue to contribute in the future

You are more than welcomed!

I did a few changes in #21124 . You may add visual test changes in future PRs.

**Comment by mustcanbedo** [comment]
@Ovilia Sorry to bother, why is there no list of contributors after my PR is merged? Also, the last fix, do you need to write some visual verification similar to before and after selection?

**Comment by Ovilia** [comment]
@mustcanbedo Hi, this PR and your id are listed in the [release note](https://github.com/apache/echarts/releases/tag/6.0.0). Where do you mean that not listed? If you mean [the contributor GitHub page](https://github.com/apache/echarts-www/graphs/contributors), I believe it only list the most contributed ones, rather than a full list.

**Comment by mustcanbedo** [comment]
@Ovilia Okay, if that's the mechanism, then I understand.
