### PR TITLE
fix(axis-log): Enable ticks under 1e-10, fixes #21099

### LINKED ISSUE #21099: [Bug] log axis ticks not containing value less than 1e-10
### Version

6.0.0-beta.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=geo-map-scatter&code=MYewdgzgLgBAJgQygmBeGBtAUDTAGAOj2LwEYB2ADgCYBWMy8gNmqfIBYBOagGhlIJtKAZnbtqedi3bC8nYQFMAtJwC6PHPgISSuvcXZ8BtasM6VaJvLUrdO5cstLD1mjIVn2mw4aarUuJiY-TgJOdlphejEfUk42J3ZXXAxSPmowoMtqHPY5dkpSWkTVLFUAbiwsEAAHKABLcDQYAG9NaABPABsFAC5WzVwACwV6gHMhqH6AclJiAFJpjVxcAHd6uCghmbm8Rc0AX2WYMYAnDf7sFYHr3FAwZHqwABkEACMFLv6oU4BXBUGMAOmmSMA6AEEAB71CCXQFtW4wKAdGp9GDTLogMZLQG4TFjABCCAgaLmx2uCGhEFeHy-N0RMAAZiBTgBbJBQBSnfqM35gYANJoACgAbgguv8AJT0hkwU4KKC_U5gGBiiUKAhQEAAUUhNXACge9XFQrwksqsuBiKtKxtoMhUJhcOuCNuyNRM3xOMR-KJJP6c0BduOJPOClhmHhuPgSAQ5JW7rRGKeCm9twgQxAqwAyh1WW8QHTGeKSUGQVgDuUgA

### Steps to Reproduce

Image

Ticks less than 1e-10 are not displayed.

This is probably caused by [fixRound](https://github.com/apache/echarts/blob/master/src/scale/Log.ts#L67) not considering the precision of the data and using 1e-10 as a fixed precision.

The correct way is to calculate the precision from data as [this example does](https://github.com/apache/echarts/blob/master/src/scale/Interval.ts#L263-L265).

### Current Behavior

No axis ticks smaller than 1e-10.

### Expected Behavior

Axis ticks like 1e-11, 1e-12, 1e-13, etc. should be displayed.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by SihongShen**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Fixes issue #21099, now axis ticks can show number smaller than 1e-10.

### Fixed issues

#21099: log axis ticks not containing value less than 1e-10

### Before: What was the problem?

No log axis ticks containing value less than 1e-10

Screenshot 2025-07-16 at 15 45 15

### After: How does it behave after the fixing?

Log axis ticks smaller then 1e-10 can be shown on the graph.

Screenshot 2025-07-16 at 15 45 49

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [x] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/scale/Log.ts [hunk 1]
```diff
@@ -64,8 +64,43 @@ class LogScale extends IntervalScale {
...
+                    const coefficientDecimals = coefficient.includes('.')
+                        ? coefficient.split('.')[1].length
+                        : 0;
+                    const exp = parseInt(exponent, 10);
+                    return exp < 0 ? Math.abs(exp) + coefficientDecimals : coefficientDecimals;
+                }
+                // Normal decimals
+                const decimalPart = str.split('.')[1];
+                return decimalPart ? decimalPart.length : 0;
+            }
```
Comment (Ovilia) [inline src/scale/Log.ts]: Calling `numberUtil.getPrecision` instead.

**Review by Ovilia — APPROVED** [review]

File: src/scale/Log.ts [hunk 2]
```diff
@@ -64,9 +64,13 @@ class LogScale extends IntervalScale {
 
         return zrUtil.map(ticks, function (tick) {
             const val = tick.value;
-            let powVal = fixRound(mathPow(base, val));
+            const rawVal = mathPow(base, val);
             let roundingCriterion = null;
 
+            // Fix #21099
+            const precision = numberUtil.getPrecisionSafe(rawVal) || 0;
+            let powVal = parseFloat(fixRound(rawVal, precision as number, true));
```
Comment (100pah) [inline src/scale/Log.ts:72]: @SihongShen @Ovilia I don't fully understand the purpose of this handling.

If `rawVal` has the fractional part digits <= 20, `rawVal` will  be equal to `powVal`, nothing changes.
Otherwise, if the fractional part digits > 20, the `number.round` method internally clamp it to 20, but that doesn't make sense in this scenario and may lead incorrect results, e.g, `(1e-40).toFixed(20)` we get `0`.

image


From my understanding, the "fix round" applied in `src/scale` is meant to correct rounding errors introduced by floating-point computation, (such as the well-known case where `0.1 + 0.2 === 0.30000000000000004`, when representing and calculating decimal fractional number in binary).

But `Math.pow(base, tick.value)` shouldn't suffer from such kind of rounding error, because the `Log.ts` guarantees `interval` and `tick.value` to be integers, and the `base` is typically an integer as well. They can be exactly represented in ieee754 64-bit floating-point number (assume no overflow - this is an separate topic).  

Therefore, there is no opportunity for rounding errors to be accumulated beyond `Number.EPSILON * Math.pow(2, ieee754_double_exponent(tick.value))` and result in a different result when converted back to a decimal string.
(Correct me if I'me wrong.)

Therefore, I think we should just remove this precision and rounding handling here. Just be:

```js
let powVal = mathPow(base, val);
```

I tried to fix it in https://github.com/apache/echarts/pull/21120
