### PR TITLE
fix(tooltip): the position of tooltip may be incorrect if appendToBody.

### LINKED ISSUE #14710: 5.1.0 tooltip位置计算错误
### Version
5.1.0

### Reproduction link
[https://codepen.io/facingcheer/pen/MWjOezN?editors=1111](https://codepen.io/facingcheer/pen/MWjOezN?editors=1111)

### Steps to reproduce
直接看tooltip的位置

### What is expected?
tooltip位置正确计算

### What is actually happening?
tooltip位置计算异常

---
导致异常的提交：
https://github.com/apache/echarts/pull/14246/files/73a9f6e7bd0bdb5b236550d968c86841555f49ee#diff-f858c6a0a46939552e35abb40ae1580141336eee77cca6485e5cff5dfe35367a

问题原因： 设置transform3d替代top和left的时候，未设置top:0 left:0 导致定位问题

### PR DESCRIPTION
**Pull request by plainheart**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

The position may be incorrect if `appendToBody` is enabled, resolves #14710.

### Fixed issues

- #14710 

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

test/new-tooltip.html

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 1]
```diff
@@ -304,8 +297,7 @@ class TooltipHTMLContent {
             document.body.appendChild(el);
         }
         else {
-            // PENDING
-            container.prepend(el);
```
Comment (pissang) [inline src/component/tooltip/TooltipHTMLContent.ts:308]: I'm not getting the purpose of this change.

**Review by pissang — APPROVED** [review]
