### PR TITLE
fix(markArea): markArea background color disappeared. close #13647

### LINKED ISSUE #13647: 区域缩放选择dataZoom导致markArea区域背景色展示不了
### Version
4.9.0

### Steps to reproduce
You can choose official demo to reproduce the bug：https://echarts.apache.org/examples/zh/editor.html?c=area-rainfall
When you select a area in the same color markArea, you will find the markArea background color disappear.
image
image

### What is expected?
it can show the markArea background color when I select a area in the same color markArea

### What is actually happening?
When you select a area in the same color markArea, you will find the markArea background color disappear.

---
When you select a area across different color markArea, you will find the markArea background color display normal.
image
image

### PR DESCRIPTION
**Pull request by Nick22nd**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

fix markArea background color disappearing when markArea inclued selected area 

### Fixed issues

- #13647: When you select a area in the same color markArea, you will find the markArea background color disappear.

### Before: What was the problem?

when selected area was included in markArea, then point would not meet condition that set allClipped to false. 

13647-before

### After: How is it fixed in this PR?

add condition that check if rectangle of markArea intersects the rectangle of display area.

13647-after

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/component/marker/MarkAreaView.ts [hunk 1]
```diff
@@ -248,22 +248,19 @@ class MarkAreaView extends MarkerView {
             const points = map(dimPermutations, function (dim) {
                 return getSingleMarkerEndPoint(areaData, idx, dim, seriesModel, api);
             });
+            const xAxis = coordSys.getAxis('x').scale.getExtent();
+            const yAxis = coordSys.getAxis('y').scale.getExtent();
+            const xPoint = [coordSys.getAxis('x').scale.parse(areaData.get('x0', idx)),
```
Comment (susiwen8) [inline src/component/marker/MarkAreaView.ts:253]: It's better to 'cache' `coordSys.getAxis('x').scale` and `coordSys.getAxis('y').scale`

File: src/component/marker/MarkAreaView.ts [hunk 2]
```diff
@@ -248,22 +248,19 @@ class MarkAreaView extends MarkerView {
...
                 return getSingleMarkerEndPoint(areaData, idx, dim, seriesModel, api);
             });
+            const xScale = coordSys.getAxis('x').scale;
+            const yScale = coordSys.getAxis('y').scale;
+            const xAxis = xScale.getExtent();
+            const yAxis = yScale.getExtent();
+            const xPoint = [xScale.parse(areaData.get('x0', idx)), xScale.parse(areaData.get('x1', idx))];
+            const yPoint = [yScale.parse(areaData.get('y0', idx)), yScale.parse(areaData.get('y1', idx))];
+            xPoint.sort();
+            yPoint.sort();
```
Comment (pissang) [inline src/component/marker/MarkAreaView.ts:258]: There is a helper to sort an array to asc order. https://github.com/apache/echarts/blob/master/src/util/number.ts#L145

Default compare function in sort will convert the values to strings and use Unicode to compare. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#parameters

File: src/component/marker/MarkAreaView.ts [hunk 3]
```diff
@@ -248,22 +248,19 @@ class MarkAreaView extends MarkerView {
             const points = map(dimPermutations, function (dim) {
                 return getSingleMarkerEndPoint(areaData, idx, dim, seriesModel, api);
             });
+            const xScale = coordSys.getAxis('x').scale;
+            const yScale = coordSys.getAxis('y').scale;
+            const xAxis = xScale.getExtent();
```
Comment (pissang) [inline src/component/marker/MarkAreaView.ts:253]: Use a more specific name here. For example `xAxisExtent`, `yAxisExtent`

**Review by pissang — CHANGES_REQUESTED** [review]

File: src/component/marker/MarkAreaView.ts (hunk 1 above)
Comment (Nick22nd) [reply src/component/marker/MarkAreaView.ts]: thanks for your advice :-)

File: src/component/marker/MarkAreaView.ts (hunk 2 above)
Comment (Nick22nd) [reply src/component/marker/MarkAreaView.ts]: thanks for helping!

**Review by pissang — APPROVED** [review]
