### PR TITLE
fix: legend visual still with decal when user set 'legend.itemStyle.decal' to 'none'

### LINKED ISSUE #16909: [Bug] legend.itemStyle.decal is invalid
### Version

5.2.1+

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=doc-example/aria-pie&version=5.2.1

### Steps to Reproduce

```
option = {
  aria: {
    enabled: true,
    decal: {
      show: true
    }
  },
  legend: {
    itemStyle: {
      decal: 'none'
    }
  },
  title: {
    text: '某站点用户访问来源',
    left: 'center'
  },
  series: [
    {
      name: '访问来源',
      type: 'pie',
      data: [
        { value: 335, name: '直接访问' },
        { value: 310, name: '邮件营销' },
        { value: 234, name: '联盟广告' },
        { value: 135, name: '视频广告' },
        { value: 1548, name: '搜索引擎' }
      ]
    }
  ]
};
```

### Current Behavior

The docs say that while legend.itemStyle.decal is set to be 'none', no decal will be used.
I've set legend.itemStyle.decal to 'none', But the decal is still visible in V5.2.1+
issue1
issue2

### Expected Behavior

as in the version 5.2.0, legend will be a solid color while legend.itemStyle.decal set 'none'

### Environment

_No response_

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by jiawulin001**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Fix the problem that the legend patterns are still with decals when user sets 'legend.itemStyle.decal' to 'none'.

### Fixed issues

- fix #16909

### Before: What was the problem?

As is described in https://github.com/apache/echarts/issues/16909#issuecomment-1104676217, `legend.itemStyle.decal` is directly overwritten by series itemStyle without checking if it's set to 'none' by user.

before#16909

### After: How is it fixed in this PR?

By adding the 'decal' into the ITEM_STYLE_KEY_MAP, Echarts now can correctly read the value of `legend.itemstyle.decal` set by users.
By checking whether user sets `legend.itemstyle.decal` to `none`, we decide whether `decal` should be overwritten by series itemStyle.

after#16909

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [x] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/model/mixin/itemStyle.ts [hunk 1]
```diff
@@ -35,7 +35,8 @@ export const ITEM_STYLE_KEY_MAP = [
     ['lineDashOffset', 'borderDashOffset'],
     ['lineCap', 'borderCap'],
     ['lineJoin', 'borderJoin'],
-    ['miterLimit', 'borderMiterLimit']
+    ['miterLimit', 'borderMiterLimit'],
+    ['decal']
```
Comment (pissang) [inline src/model/mixin/itemStyle.ts:39]: This underlying method maps the `itemStyle` in echarts to the style object in zrender.

But `decal` in echarts is different with `decal` in zrender. In echarts it's an object that describe how the decal looks like. But in zrender it's a image that rendered as [pattern](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createPattern) on top of the element.  So we didn't include `decal` here directly. Instead the decal property is created in https://github.com/apache/echarts/blob/4a52199842039d7fa6019ee8584d1a395fbc771a/src/visual/decal.ts#L44

Comment (jiawulin001) [reply src/model/mixin/itemStyle.ts:39]: Thank you for pointing it out. I agree I should use it to deal with interface `decal`. But the problem is that I cannot find other function than https://github.com/apache/echarts/blob/4a52199842039d7fa6019ee8584d1a395fbc771a/src/component/legend/LegendView.ts#L565
But `getItemStyle()` will only pick the attributes in the list of ITEM_STYLE_KEY_MAP. The only other way I think is to directly visit the decal attribute level by level, which I think is not elegant enough. And it could be risky if we call a structure like `legendItemModel.ecModel.option.legend[0].itemStyle.decal`, because if any structure in between does not exist or has changed, it could result in unstability. Is there any good one to pick the attribute `decal` without adding it to the list of ITEM_STYLE_KEY_MAP?

Comment (pissang) [reply src/model/mixin/itemStyle.ts:39]: Using `Model#get` or `Model#getShallow` is the best way to access the property in the option. `getItemStyle` is also using `Model#getShallow` at the bottom.

https://github.com/apache/echarts/blob/f9bd8da1884492fdfa234a95df86ff5605708bda/src/model/mixin/makeStyleMapper.ts#L46

These two method works like optional chaining operator. Some examples:
```ts
// Get the itemStyle object in series.
seriesModel.getShallow('itemStyle')
// Get itemStyle.color value in series. Similar to seriesModel.option?.itemStyle?.color
seriesModel.getShallow(['itemStyle', 'color'])
```

The difference between `Model#get` and `Model#getShallow` is `Model#get` will also consider cascading. If we didn't find `itemStyle.color` in the data level, it will keep finding in the series level and global option level.

There is another method `Model#getModel` will wrap a new model after getting the value:

```
const itemStyleModel = seriesModel.getModel('itemStyle');
// itemStyleModel is now in the itemStyle scope
const color = itemStyleModel.get('color');
```

Comment (jiawulin001) [reply src/model/mixin/itemStyle.ts:39]: Thank you for your detailed explanation! My appreciate for your patience.
Now I use `getShallow` to get `decal` and use `createOrUpdatePatternFromDecal` to deal with it. But one last thing is to get `api` for `createOrUpdatePatternFromDecal`, which I found to be at `legendItemModel.ecModel.scheduler.api`. Is there a better way to access it?

Comment (pissang) [reply src/model/mixin/itemStyle.ts:39]: `api` will be given in the `render` method 
https://github.com/apache/echarts/blob/72f4c419ae59e738740987b0d6affde96bca7f4b/src/component/legend/LegendView.ts#L100
You can pass it down to other methods if the method needs it.

BTW: I was wrong about `Model#get` and `Model#getShallow`. Just updated in the previous comment. `get(path, false)` in your commited code is the way to ignore option cascading.

Comment (jiawulin001) [reply src/model/mixin/itemStyle.ts]: Just updated the code. I think I used `getShallow` in code and as I track the dataflow, it traces back to parent model if option is not found. So I think it works well in the code.

File: src/component/legend/LegendView.ts [hunk 2]
```diff
@@ -564,8 +568,14 @@ function getLegendStyle(
     const legendItemModel = legendModel.getModel('itemStyle') as Model<LegendItemStyleOption>;
     const itemStyle = legendItemModel.getItemStyle();
     const iconBrushType = iconType.lastIndexOf('empty', 0) === 0 ? 'fill' : 'stroke';
+    const decalStyle = legendItemModel.getShallow('decal', false);
+    if (!decalStyle || decalStyle === 'inherit') {
```
Comment (pissang) [inline src/component/legend/LegendView.ts:572]: I will prefer using a ternary expression here for less code:
```ts
itemStyle.decal = !decalStyle || decalStyle === 'inherit' 
  ? itemVisualStyle.decal
  : createOrUpdatePatternFromDecal(decalStyle, api)

Comment (jiawulin001) [reply src/component/legend/LegendView.ts]: For sure.

File: src/component/legend/LegendView.ts [hunk 3]
```diff
@@ -564,8 +568,11 @@ function getLegendStyle(
     const legendItemModel = legendModel.getModel('itemStyle') as Model<LegendItemStyleOption>;
     const itemStyle = legendItemModel.getItemStyle();
     const iconBrushType = iconType.lastIndexOf('empty', 0) === 0 ? 'fill' : 'stroke';
+    const decalStyle = legendItemModel.getShallow('decal', false);
```
[the remark this answers is not in the document]
Comment (pissang) [reply src/component/legend/LegendView.ts:571]: Also could you help rename these confusing variables:

`legendModel` should be `legendItemModel`
`legendItemModel` should be `itemStyleModel`

[the remark this answers is not in the document]
Comment (jiawulin001) [reply src/component/legend/LegendView.ts:571]: > So here we should not passing false to second parameter.

`false` here means not to ignore parent, `decal` is in `legend.itemStyle` so we should pass in `false` to allow it to search in parent model.

>Also could you help rename these confusing variables:

Sure can do.

[the remark this answers is not in the document]
Comment (pissang) [reply src/component/legend/LegendView.ts:571]: > false here means not to ignore parent, decal is in legend.itemStyle so we should pass in false to allow it to search in parent model.

Sorry my mistake. It's an optional parameter and by default it will search in parent model. So my brain thought you want to stop it when saw the second parameter is used. But still this `false` can be removed because it's the default value.

[the remark this answers is not in the document]
Comment (jiawulin001) [reply src/component/legend/LegendView.ts]: > But still this `false` can be removed because it's the default value.

Hmmm, I am not sure but I think passing `false` explicitly can help debugging in the future. I respect your decision though. Will remove it.

**Review by pissang — APPROVED** [review]

File: src/component/legend/LegendView.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (pissang) [reply src/component/legend/LegendView.ts]: > Hmmm, I am not sure but I think passing false explicitly can help debugging in the future

Default means it's the most common used value(here it's more than 90% of the code). Usually we should respect the default and only override it when we know what we are doing in special cases.

[the remark this answers is not in the document]
Comment (jiawulin001) [reply src/component/legend/LegendView.ts]: I see, thank you for your explanation and suggestions.
