### PR TITLE
fix(dataZoom): restrict range on brushEnd

### LINKED ISSUE #20807: [Bug] maxSpan cannot restrict the span selected via brush
### Version

latest

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=area-simple&code=DYUwLgBARghgziCBeCBqAdiA7hAIjMEACgEYBOANgA4AaCMugZgEoBuAKFEgHtN8BPZBABMAFggAqCIwoAGWZIgl5sjlwgATAohQBtALprwmgjCG6AsgQAWAOgBOMdBu4BbIs0WN5h9gDNuewgidQBLIRJWCHCAHhEVVWjUVE8Ab3YICAA3GCD0bhwUTBx8QiIiWAQ0FF4QAWY2DJNCWwAHAFc4ayJdfKxbAHNwADF24GAATRBcjzo-wfALXjBuz1QlOYKFsFLiZn1bACtuUPQiAHIAenOGjkytMBg2zu6rFYdududyt7tHZzcHggAFoILJbABWTxSYQKdYPGC6cKgkj6W7sAC-7G4rTAoV4QnSmTA3G4wDxrQAXBAiZkIGB7KEBkN7NTzjAAB6hODnGhNTKtbhwUJ43jUvxfADGovQwVxaX5dPs4Ha9llulxulk-jo52UAFJzr46RAsZkMXziSLQNTaZlQH4wGzJSB0IR7LzFYQOU6IOcADK5IYQACCyrMAGFrLkwOcmhamhyQ1y4LavfxWiBndoBoF-J6TVBPs5cvwAOIwKkQPwwYAIS10hHUh4geMN_jJ7lpk1gDNZv05YDtEAFulFr5aezlyvUrW65SyQ36NtNBEALVJrlnirtdMul3pfbZp2FGhHDZNcEe9l9sgvdNdGmpynvmVcpwAyq0nNSIa-IK4nJfj-SiyIqCYmruxJHn6J6hGeo6Xtet7_o-z53oqb6ft-6C_v-gEcsBuGgeBTQ6k0CCMiAqYQLoO6YRA6AwK4_bnMMMAANaIKUMCIXSvaZmywCnOeDFwPwrhFsAbL5JgfGZHAzGtMJ6ADEJYBgFA8nRIQrgfr2No0gxmSSmSgRsvYAxQEQwgQn-EAAOx3kojAkMwcYmua_65NM-n8IZUF0qZwDmYx2AQCAkrRjecCDI4rTWKEkq2P6Im5GWjgaKErpgEQzn5XQJB0HRnmeYFpXcH4fgIChxmecFoXnJZ1m2fZJAQrQEDUO5dVeb1RmlRVVU1c-_6lQ1rJ-s1Nl2XQTmFa5PWDXSZqDWiDEQZ5TbNDApGZMuGKsEAA

### Steps to Reproduce

1. set maxSpan for dataZoom
2. drag via handler or click the brush both works
3. brushSelect not works with maxSpan

### Current Behavior

brush could selected without restrict

### Expected Behavior

brush could select with restrict

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
- Framework: React
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by mortalYoung**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

- minMaxSpan could restrict brushSelect

### Fixed issues

fixed #20807 

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/component/dataZoom/SliderZoomView.ts [hunk 1]
```diff
@@ -999,7 +999,15 @@ class SliderZoomView extends DataZoomView {
...
-        this._handleEnds = [brushShape.x, brushShape.x + brushShape.width];
+        // Restrict range.
+        const minMaxSpan = this.dataZoomModel.findRepresentativeAxisProxy().getMinMaxSpan();
+
+        sliderMove(0, this._range, viewExtend, 0, minMaxSpan.minSpan, minMaxSpan.maxSpan);
+
+        this._handleEnds = [
+            linearMap(this._range[0], [0, 100], viewExtend, true),
+            linearMap(this._range[1], [0, 100], viewExtend, true)
+        ];
```
Comment (100pah) [inline src/component/dataZoom/SliderZoomView.ts:1011]: - In this sentence `sliderMove(0, this._range, viewExtend, 0, minMaxSpan.minSpan, minMaxSpan.maxSpan);`
the `viewExtent` is pixel value while `this._range` is percent value. They do not match.
- `[0, 100]` has been defined as a variable above `const percentExtent = [0, 100];`, thus should use it directly.

Follow what data zoom drag did, the complete code can be:

```js
        const viewExtend = this._getViewExtent();
        const percentExtent = [0, 100];

        const handleEnds = this._handleEnds = [brushShape.x, brushShape.x + brushShape.width];
        const minMaxSpan = this.dataZoomModel.findRepresentativeAxisProxy().getMinMaxSpan();
        // Restrict range.
        sliderMove(
            0,
            handleEnds,
            viewExtend,
            0,
            minMaxSpan.minSpan != null
                ? linearMap(minMaxSpan.minSpan, percentExtent, viewExtend, true) : null,
            minMaxSpan.maxSpan != null
                ? linearMap(minMaxSpan.maxSpan, percentExtent, viewExtend, true) : null
        );

        this._range = asc([
            linearMap(handleEnds[0], viewExtend, percentExtent, true),
            linearMap(handleEnds[1], viewExtend, percentExtent, true)
        ]);

        this._updateView();

        this._dispatchZoomAction(false);

```

**Review by 100pah — CHANGES_REQUESTED** [review]

**Review by 100pah — APPROVED** [review]
