### PR TITLE
fix(marker): marker state not restore after blur

### LINKED ISSUE #16665: [Bug] type='line'中的emphasis.focus触发后不能正确恢复状态
### Version

5.3.0

### Link to Minimal Reproduction

_No response_

### Steps to Reproduce

```option = {
  yAxis: [
    {
      type: 'value',
    }
  ],
  xAxis: [
    {
      type: 'value',
      data: [
        0, 625, 1250, 1875, 2500, 3125, 3750, 4375, 5000, 5625, 6250, 6875,
        7500, 8125, 8750, 9375, 10000, 10625, 11250, 11875, 12500, 13125, 13750,
        14375
      ],
    }
  ],
  series: [
    {
      type: 'line',
      name: 'PL_PC_P1',
      data: [
        [0, 14],
        [625, 14],
        [1250, 14],
        [1875, 14],
        [2500, 15],
     
      ],
      emphasis: {
        focus: 'series'
      },
      markPoint: {
        data: [
          {
            value: 128,
            xAxis: 1120,
            yAxis: 14,
          }
        ]
      }
    },
    {
      type: 'line',
      name: 'PL_PC_P',
      emphasis: {
        focus: 'series',
      },
      data: [
        [0, 15],
        [625, 15],
        [1250, 15],
        [1875, 15],
        [2500, 14],
        [3125, 15],
        [3750, 15],
    
      ]
    }
  ]
};
```

### Current Behavior

鼠标移到绿线[name = PL_PC_P]上触发高亮后 鼠标移走 蓝线[name = PL_PC_P1]的markpoint没有回复到普通状态 

(expected)
图片

(actually)
图片

### Expected Behavior

鼠标移走后 期望恢复蓝线[name = PL_PC_P1]的markpoint到普通状态

### Environment

```markdown
- OS: macOS 11.4
- Browser: Firefox
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Set component's blur state to true when compoonent is blured

### Fixed issues

- Close #16665 

### Before: What was the problem?

Kapture 2022-03-12 at 16 23 20

### After: How is it fixed in this PR?

Kapture 2022-03-12 at 16 20 27

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [x] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/util/states.ts [hunk 1]
```diff
@@ -520,6 +520,7 @@ export function blurSeries(
         }
         const view = api.getViewOfComponentModel(componentModel);
         if (view && view.blurSeries) {
+            getComponentStates(componentModel).isBlured = true;
```
Comment (pissang) [inline src/util/states.ts:523]: The logic here is for the markPoint/markLine/markArea component to blur the makers elements in the `blurredSeries`. It's not blur the component itself. 

Marking this `componentModel` to `isBlured` means the component model needs to be blurred. It's not exactly the same. 

What's more correct is providing a method  like`unblurSeries` in the `MarkerView` that do the opposite operation and call it in the `allLeaveBlur` methods.

File: src/component/marker/MarkerView.ts [hunk 2]
```diff
@@ -88,6 +88,23 @@ abstract class MarkerView extends ComponentView {
         });
     }
 
+    leaveBlurSeries(seriesModelList: SeriesModel[]) {
```
Comment (susiwen8) [inline src/component/marker/MarkerView.ts:91]: @pissang Can we merge `blurSeries` and `leaveBlurSeries`?

Comment (pissang) [reply src/component/marker/MarkerView.ts:91]: I'm not sure how to do this. But I think these two may not be invoked in the same stage an it's better to keep them separated

File: src/util/states.ts [hunk 3]
```diff
@@ -427,17 +428,22 @@ function shouldSilent(el: Element, e: ElementEvent) {
...
         if (componentStates.isBlured) {
-            const view = componentType === 'series'
-                ? api.getViewOfSeriesModel(componentModel as SeriesModel)
-                : api.getViewOfComponentModel(componentModel);
             // Leave blur anyway
             view.group.traverse(function (child) {
                 singleLeaveBlur(child);
             });
         }
+        if (view && (view as ComponentView).leaveBlurSeries) {
```
Comment (pissang) [inline src/util/states.ts:444]: `leaveBlurSeries` should be called after all `leaveBlurredSeries` is collected.

File: src/util/states.ts [hunk 4]
```diff
@@ -427,17 +428,22 @@ function shouldSilent(el: Element, e: ElementEvent) {
 
 export function allLeaveBlur(api: ExtensionAPI) {
     const model = api.getModel();
+    const leaveBlurredSeries: SeriesModel[] = [];
     model.eachComponent(function (componentType, componentModel) {
         const componentStates = getComponentStates(componentModel);
+        const view = componentType === 'series'
```
Comment (pissang) [inline src/util/states.ts:434]: `componentType === 'series'` is better to be cached in a variable `isSeries`

File: src/component/marker/MarkerView.ts (hunk 2 above)
Comment (pissang) [reply src/component/marker/MarkerView.ts:91]: If merging means putting the shared logic in a utility method like `toggleSeriesBlur` and use it with a flag in `blurSeries` and `leaveBlurSeries`. It's a great idea and we should do this.

File: src/util/states.ts [hunk 5]
```diff
@@ -427,19 +428,32 @@ function shouldSilent(el: Element, e: ElementEvent) {
...
-            const view = componentType === 'series'
-                ? api.getViewOfSeriesModel(componentModel as SeriesModel)
-                : api.getViewOfComponentModel(componentModel);
             // Leave blur anyway
             view.group.traverse(function (child) {
                 singleLeaveBlur(child);
             });
         }
+        if (view && (view as ComponentView).toggleBlurSeries) {
+            (view as ComponentView).toggleBlurSeries(leaveBlurredSeries, false, model);
```
Comment (pissang) [inline src/util/states.ts:447]: This code can be removed

File: src/util/states.ts [hunk 6]
```diff
@@ -427,19 +428,32 @@ function shouldSilent(el: Element, e: ElementEvent) {
...
     const model = api.getModel();
+    const leaveBlurredSeries: SeriesModel[] = [];
+    const allComponents: ComponentModel[] = [];
     model.eachComponent(function (componentType, componentModel) {
         const componentStates = getComponentStates(componentModel);
+        const isSeries = componentType === 'series';
+        const view = isSeries ? api.getViewOfSeriesModel(componentModel as SeriesModel)
+            : api.getViewOfComponentModel(componentModel);
+        !isSeries && allComponents.push(componentModel);
+        isSeries && leaveBlurredSeries.push(componentModel as SeriesModel);
```
Comment (pissang) [inline src/util/states.ts:439]: Seems we only need to add `componentModel` to `leaveBlurredSeries` when `componentStates.isBlured`

File: src/util/states.ts [hunk 7]
```diff
@@ -427,19 +427,29 @@ function shouldSilent(el: Element, e: ElementEvent) {
...
 export function allLeaveBlur(api: ExtensionAPI) {
     const model = api.getModel();
+    const leaveBlurredSeries: SeriesModel[] = [];
+    const allComponents: ComponentModel[] = [];
     model.eachComponent(function (componentType, componentModel) {
         const componentStates = getComponentStates(componentModel);
+        const isSeries = componentType === 'series';
+        const view = isSeries ? api.getViewOfSeriesModel(componentModel as SeriesModel)
+            : api.getViewOfComponentModel(componentModel);
+        !isSeries && allComponents.push(componentModel);
```
Comment (pissang) [inline src/util/states.ts:437]: Seems we can save view instead of model here directly and there is no need to use `getViewOfComponentModel` in the following code again.

**Review by pissang — APPROVED** [review]
