### PR TITLE
fix(sanky):fallback to black if color were illegal

### LINKED ISSUE #16574: 桑基图option.color设置为数组，数组中颜色为空字符串时，报错
### Version

5.3.0

### Link to Minimal Reproduction

_No response_

### Steps to Reproduce

option  = {
      series: [
          type: 'sankey',
         ......
     ],
    color: ['red', '']
}

### Current Behavior

颜色中带有空字符串时报错，目前只发现桑基图报错，饼图、散点图等其他图表不报错。

### Expected Behavior

不报错

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

if `zrColor.parse` returns `undefiend`, use `#000` as default color

### Fixed issues

- Close #16574

### Before: What was the problem?

Screen Shot 2022-03-02 at 10 31 52 PM

### After: How is it fixed in this PR?

Screen Shot 2022-03-02 at 10 31 19 PM

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/visual/VisualMapping.ts [hunk 1]
```diff
@@ -693,7 +694,11 @@ function setVisualToOption(thisOption: VisualMappingInnerOption, visualArr: Visu
     thisOption.visual = visualArr;
     if (thisOption.type === 'color') {
         thisOption.parsedVisual = zrUtil.map(visualArr, function (item: string) {
-            return zrColor.parse(item);
+            const color = zrColor.parse(item);
+            if (!color && __DEV__) {
+                warn(`'${item}' is an illegal color, fallback to '#000000'`, true);
+            }
+            return zrColor.parse(item) || [0, 0, 0, 1];
```
Comment (pissang) [inline src/visual/VisualMapping.ts:701]: Should be color here?

Comment (susiwen8) [reply src/visual/VisualMapping.ts]: Right.

**Review by pissang — APPROVED** [review]
