### PR TITLE
fix: tooltip content changes with axis extent when 'triggerOn' set to 'click'

### LINKED ISSUE #16930: [Bug] Tooltip formatter gives wrong values
### Version

Bug appeared in v.5.2.0 and still is in latest version (v5.3.2)

### Link to Minimal Reproduction

https://codepen.io/meredev/pen/OJzqwNg

### Steps to Reproduce

1. **Zoom on the chart** with the mouse wheel (to see just a few of the points)
2. **Click somewhere on the chart** -> a vertical dashed-line appears (at a given x) and the tooltip shows the right value (for that x)
3. **Pan to the left or the right** -> the dashed-line is still where it's supposed to be (at the same x), but the tooltip doesn't show the right value (it shows the value for another x instead).  
  
Here is a visualization of the steps to follow (click to expand) :
Bug report
 

### Current Behavior

The tooltip is not displaying the value it's supposed to (the one along the axisPointer). If you move the chart to a side (=pan), the axisPointer stays on the point (here x=13) BUT the tooltip doesn't display the value of this point. In the screenshot below, we see that it displays y=900 (which is the value of x=15) instead of showing y=377 (which is the value for x=13).    
  
behavior

When looking to the `params` object of the formatter function (with console.log), we can clearly see that `axisValue` (which is good) doesn't fit with `value` or `name` ...  
  
Formatter function `params` object :  

Formatter params object

### Expected Behavior

It should display the value of the point that is on the axisPointer (the vertical dashed-line). If you move the chart to a side (=pan), the axisPointer stays on the point (that already works) BUT the tooltip should display the value of this point.  
In the `params` object of the formatter function,  `axisValue` should be the same as `name`, and should fit with `data`, `dataIndex` and `value`.

### Environment

```markdown
- OS:Windows 10
- Browser: Chrome
- Framework: Vue 2
```

### Any additional comments?

This worked prior to v5.2.0 (I tried with v.5.1.2 and it worked as expected)  
  

After digging a bit more in this bug, i think the formatter function should not even be called when zooming or panning (since the values to display in the tooltip stay the same, there is no reason to call the tooltip formatter function).

### PR DESCRIPTION
**Pull request by jiawulin001**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?
Fix the problem that the tooltip changes as the axis extent changes when `triggerOn` is set to `click`

### Fixed issues

- fix #16930

### Before: What was the problem?

When `tooltip.triggerOn` is set to `'click'`, tooltip is expected to stay the same until user clicks another item. But the tool tip content will change with axis extent now after zooming in and slide the axis around. The reason causing this is stated in https://github.com/apache/echarts/issues/16930#issuecomment-1107786045

before#16930

### After: How is it fixed in this PR?

The content of tooltip will stay the same until user clicks another item.

after#16930

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [x] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/component/tooltip/TooltipView.ts [hunk 1]
```diff
@@ -257,6 +257,7 @@ class TooltipView extends ComponentView {
             // self.manuallyShowTip({x, y}) might cause tooltip hide,
             // which is not expected.
             && tooltipModel.get('triggerOn') !== 'none'
+            && tooltipModel.get('triggerOn') !== 'click'
```
Comment (pissang) [inline src/component/tooltip/TooltipView.ts:260]: It will be better to cache the `tooltipModel.get('triggerOn')` to a temporal variable `triggerOn` if there are multiple accesses.

**Review by pissang — APPROVED** [review]
