### PR TITLE
<fix>(tooltip): fix alwaysShowContent doesn't work after leaving the …

### LINKED ISSUE #18111: [Bug] alwaysShowContent: true, 设置了不生效 还是会从tooltip里离开后失效
### Version

5.33

### Link to Minimal Reproduction

_No response_

### Steps to Reproduce

[Bug]           alwaysShowContent: true, 设置了不生效 还是会从tooltip里离开后失效

### Current Behavior

[Bug]           alwaysShowContent: true, 设置了不生效 还是会从tooltip里离开后失效

### Expected Behavior

设置了 alwaysShowContent: true, tootip会一直显示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by jianghaoran116**
…tooltip  . close #18111

## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 1]
```diff
@@ -336,7 +337,7 @@ class TooltipHTMLContent {
             self._inContent = false;
 
             if (self._enterable) {
-                if (self._show) {
+                if (self._show && !self._alwaysShowContent) {
```
Comment (Ovilia) [inline src/component/tooltip/TooltipHTMLContent.ts:340]: I think it's more rust to check this in `hideLater` rather than `onmouseleave` because when other reasons triggers hiding, this should also be checked.

**Review by Ovilia — CHANGES_REQUESTED** [review]
Thanks for the contribution!

I think `TooltipRichContent` should also make similar changes. And the `manuallyHideTip` in `TooltipView` should remove the checking of `!this._alwaysShowContent` since we've done the checking in `hideLater`. And thus `this._alwaysShowContent` variable may probably be needed in `TooltipView` any more.

Please also add a [test case](https://github.com/apache/echarts/wiki/How-to-make-a-pull-request#test) for this PR.

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 1 above)
Comment (jianghaoran116) [reply src/component/tooltip/TooltipHTMLContent.ts:340]: get it

File: src/component/tooltip/TooltipView.ts [hunk 2]
```diff
@@ -147,7 +147,7 @@ class TooltipView extends ComponentView {
 
     private _api: ExtensionAPI;
 
-    private _alwaysShowContent: boolean;
+    // private _alwaysShowContent: boolean;
```
Comment (Ovilia) [inline src/component/tooltip/TooltipView.ts:150]: Remove this.

File: src/component/tooltip/TooltipView.ts [hunk 3]
```diff
@@ -200,7 +200,7 @@ class TooltipView extends ComponentView {
          * @private
          * @type {boolean}
          */
-        this._alwaysShowContent = tooltipModel.get('alwaysShowContent');
+        // this._alwaysShowContent = tooltipModel.get('alwaysShowContent');
```
Comment (Ovilia) [inline src/component/tooltip/TooltipView.ts:203]: Remove these 5 lines.

**Review by Ovilia — CHANGES_REQUESTED** [review]
Looks good to me other than some unnecessary comments.

File: src/component/tooltip/TooltipView.ts (hunk 3 above)
Comment (jianghaoran116) [reply src/component/tooltip/TooltipView.ts:203]: got it

**Review by Ovilia — APPROVED** [review]
Thanks for your contribution!
