### PR TITLE
bug(tooltip): tooltip arrow will follow borderWidth. close #14373

### LINKED ISSUE #14373: [bug] tooltip arrow should follow the specified `borderWidth`
### Version
5.0.2

### Reproduction link
https://www.makeapie.com/editor.html?c=xLv-60nCLP&v=1

### Steps to reproduce
Hover on the scatter, the arrow isn't following the specified `borderWidth`.

### What is expected?
The arrow should follow the specified `borderWidth`.

### What is actually happening?
The arrow always keeps a 1px border and target position is incorrect.

### PR DESCRIPTION
**Pull request by g7i**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?
Tooltip arrow will follow the specified `borderWidth` in tooltip.

### Fixed issues

fixes: #14373

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

Checkout `test/scatter.html`

### Merging options

- [x] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by g7i** [comment]
Hey, do I need to resolve the conflicts or the maintainer will resolve?

**Comment by pissang** [comment]
@g7i Hi, It will be great if you can resolve the conflicts

**Comment by pissang** [comment]
@g7i Please don't commit the files in `dist` and `i18n` folder. They are only updated before release

**Comment by g7i** [comment]
> @g7i Please don't commit the files in `dist` and `i18n` folder. They are only updated before release

Ohh okay, sorry did it by mistake. Now reverted the the changes. Thanks....

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 1]
```diff
@@ -111,6 +114,8 @@ function assembleTransform(x: number, y: number, toString?: boolean) {
     // If using float on style, the final width of the dom might
     // keep changing slightly while mouse move. So `toFixed(0)` them.
     const x0 = x.toFixed(0) + 'px';
+    // To keep the tooltip slightly above
+    y -= 5;
```
Comment (pissang) [inline src/component/tooltip/TooltipHTMLContent.ts:118]: What if tooltip is on the bottom/left/right?

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 2]
```diff
@@ -60,28 +60,31 @@ function mirrorPos(pos: string): string {
...
+    const borderWidth = tooltipModel.get('borderWidth');
+
     if (!isString(arrowPosition) || arrowPosition === 'inside') {
         return '';
     }
 
     borderColor = convertToColorString(borderColor);
     const arrowPos = mirrorPos(arrowPosition);
-    let positionStyle = `${arrowPos}:-6px;`;
+    let positionStyle = `${arrowPos}:-10px;`;
```
Comment (pissang) [inline src/component/tooltip/TooltipHTMLContent.ts:76]: What is this change for?

Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts:76]: When I increased the `borderWidth` of the arrow, the placement is slightly off. So in order to adjust it I made this change.
If there is any better way please suggest me.

Thanks....

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 1 above)
Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts:118]: Ahh I didn't consider it. Let me rework on it. Thanks...

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 2 above)
Comment (pissang) [reply src/component/tooltip/TooltipHTMLContent.ts:76]: If it is related to user-set `borderWidth`. I think it's better to calculate this value from `broderWidth`

Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts:76]: Yeah, on it.
Since the square of the arrow is rotated need to calculate the diagonal.

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 1 above)
Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts]: Fixed automatically when I adjusted the calculations for the comment below. So removed it.

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 2 above)
Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts]: Fixed it :exclamation:

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 3]
```diff
@@ -60,17 +60,21 @@ function mirrorPos(pos: string): string {
...
 
 function assembleArrow(
-    backgroundColor: ColorString,
+    tooltipModel: Model<TooltipOption>,
     borderColor: ZRColor,
     arrowPosition: TooltipOption['position']
 ) {
+    const backgroundColor = tooltipModel.get('backgroundColor');
+    const borderWidth = tooltipModel.get('borderWidth');
+
```
Comment (susiwen8) [inline src/component/tooltip/TooltipHTMLContent.ts:69]: Just notice a very small thing, could it move this after `if` statement? Since it only affect whatever after `if`.

Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts]: Fixed :exclamation:

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 4]
```diff
@@ -81,15 +85,23 @@ function assembleArrow(
...
+        `background-color:${backgroundColor};`
     ];
+
+    const shadowBlur = tooltipModel.get('shadowBlur');
+    const shadowColor = tooltipModel.get('shadowColor');
+    const shadowOffsetX = tooltipModel.get('shadowOffsetX');
+    const shadowOffsetY = tooltipModel.get('shadowOffsetY');
+    const boxShadow = `${shadowOffsetX}px ${shadowOffsetY}px ${shadowBlur}px ${shadowColor}`;
+
+    styleCss.push('box-shadow:' + boxShadow);
```
Comment (plainheart) [inline src/component/tooltip/TooltipHTMLContent.ts:103]: If we add `box-shadow` for the arrow, it will look unexpectedly obvious. I'm not sure whether we should disable shadow of arrow.

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 5]
```diff
@@ -60,17 +60,21 @@ function mirrorPos(pos: string): string {
...
     }
 
+    const backgroundColor = tooltipModel.get('backgroundColor');
+    const borderWidth = tooltipModel.get('borderWidth');
+
     borderColor = convertToColorString(borderColor);
     const arrowPos = mirrorPos(arrowPosition);
-    let positionStyle = `${arrowPos}:-6px;`;
+    const arrowSize = borderWidth >= 5 ? borderWidth : 5;
+    let positionStyle = `${arrowPos}:-${Math.sqrt(2 * arrowSize * arrowSize) / 2 + borderWidth}px;`;
```
Comment (plainheart) [inline src/component/tooltip/TooltipHTMLContent.ts:77]: The position of arrow seems not so accurated(shown as previous screenshot). We may need to minus half of the border width.

And the calculated number may have many decimal places, it would be better to fix it as an integer or remain two decimal places.

**Review by plainheart — CHANGES_REQUESTED** [review]

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 4 above)
Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts:103]: So, should I remove the shadow?

Comment (plainheart) [reply src/component/tooltip/TooltipHTMLContent.ts:103]: Please @pissang @susiwen8 take a look.

Comment (pissang) [reply src/component/tooltip/TooltipHTMLContent.ts:103]: I remember we dicussed it before and I prefereed not having shadow here. I'm not sure if there is a better solution.

Comment (pissang) [reply src/component/tooltip/TooltipHTMLContent.ts:103]: Perhaps we need CSS `clip-path` like described in https://stackoverflow.com/questions/43863785/css-arrow-with-border-add-box-shadow/43863886

Comment (plainheart) [reply src/component/tooltip/TooltipHTMLContent.ts:103]: `clip-path` should work. However, it seems to have poor compatibility.

Comment (pissang) [reply src/component/tooltip/TooltipHTMLContent.ts:103]: @plainheart https://developer.mozilla.org/zh-CN/docs/Web/CSS/clip-path Major browsers except for IE already support it well. It is acceptable having some small issue on IE to have a better experience on other major browsers IMO. Of course, it will be perfect to have other solutions both keep compatibility, simple implementation(no too much code), and good result.

Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts:103]: One quick question, how am I supposed to use pseudo-elements in inline style? Is there any way or linked stylesheet so that I can add them there?
Thanks

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 5 above)
Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts:77]: You mean horizontal placement right?

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 4 above)
Comment (pissang) [reply src/component/tooltip/TooltipHTMLContent.ts:103]: @g7i I don't think it's possible to use pseudo-elements in inline style. So the top solution in my StackOverflow link can't be used in our case. Instead the second solution which uses `clip-path` is possible here. We can apply `clip-path` on our arrow element.

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 5 above)
Comment (plainheart) [reply src/component/tooltip/TooltipHTMLContent.ts:77]: It seems both horizontal and vertical positions are off a bit. I think the position of arrow is correct(vertical middle / horizontal center of the tooltip container), but the position of the tooltip container is not correct, it should consider arrow size when transforming the container's x/y.

Comment (pissang) [reply src/component/tooltip/TooltipHTMLContent.ts:77]: @g7i Hi, any updates on this offset issue?

Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts:77]: I'm almost done with it. By tomorrow EOD will update the PR.
Thank you

Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts:77]: I'm almost done with it. Will update the PR by tomorrow EOD.
Thank you

Comment (pissang) [reply src/component/tooltip/TooltipHTMLContent.ts:77]: @g7i Great!

Comment (plainheart) [reply src/component/tooltip/TooltipHTMLContent.ts:77]: Good job! We'll help review it ASAP. 👍

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 6]
```diff
@@ -60,17 +60,21 @@ function mirrorPos(pos: string): string {
...
         return '';
     }
 
+    const backgroundColor = tooltipModel.get('backgroundColor');
+    const borderWidth = tooltipModel.get('borderWidth');
+
     borderColor = convertToColorString(borderColor);
     const arrowPos = mirrorPos(arrowPosition);
-    let positionStyle = `${arrowPos}:-6px;`;
+    const arrowSize = borderWidth >= 5 ? borderWidth : 5;
```
[the remark this answers is not in the document]
Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts:76]: I think we're not modifying `borderWidth`, just the `size of the arrow` if borderWidth is less than 5 because below this the arrow is very very small and looking weird.
Do you think I should remove it?

[the remark this answers is not in the document]
Comment (plainheart) [reply src/component/tooltip/TooltipHTMLContent.ts:76]: I think so. Because it will look weird if we set a small `borderWidth`, for example, `1`.

[the remark this answers is not in the document]
Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts:76]: So, for smaller borderwidth I'll handle position in an `if` condition. Is this fine?

[the remark this answers is not in the document]
Comment (plainheart) [reply src/component/tooltip/TooltipHTMLContent.ts:76]: Can have a try.

**Comment by pissang** [comment]
Seems we can't make it merged in 5.1.2. Moved to the next 5.2.0

**Comment by g7i** [comment]
Okay, thanks. I was away for a while that's why unable to work on it. Will fix it asap.

File: src/component/tooltip/TooltipView.ts [hunk 7]
```diff
@@ -1100,20 +1101,20 @@ function calcTooltipPosition(
             y = rect.y + rectHeight / 2 - domHeight / 2;
             break;
         case 'top':
-            x = rect.x + rectWidth / 2 - domWidth / 2;
+            x = rect.x + rectWidth / 2 - domWidth / 2 - borderWidth / 2;
```
[the remark this answers is not in the document]
Comment (g7i) [reply src/component/tooltip/TooltipView.ts:1104]: :heavy_check_mark:

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts:76]: :heavy_check_mark:

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts:77]: :heavy_check_mark:

File: src/component/tooltip/TooltipView.ts [hunk 8]
```diff
@@ -1084,7 +1084,8 @@ function confineTooltipPosition(
 function calcTooltipPosition(
     position: TooltipOption['position'],
     rect: ZRRectLike,
-    contentSize: number[]
+    contentSize: number[],
+    borderWidth: number
 ): [number, number] {
```
[the remark this answers is not in the document]
Comment (g7i) [reply src/component/tooltip/TooltipView.ts:1089]: :heavy_check_mark:

**Comment by g7i** [comment]
@pissang @plainheart I have addressed all the comments for changes. Please re-review it. Thank you.

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 9]
```diff
@@ -81,15 +85,15 @@ function assembleArrow(
         transformStyle += `translateX(-50%) rotate(${arrowPos === 'top' ? 225 : 45}deg)`;
     }
 
-    const borderStyle = `${borderColor} solid 1px;`;
+    const borderStyle = `${borderColor} solid ${borderWidth}px;`;
     const styleCss = [
-        'position:absolute;width:10px;height:10px;',
+        `position:absolute;width:${borderWidth}px;height:${borderWidth}px;`,
```
Comment (pissang) [inline src/component/tooltip/TooltipHTMLContent.ts:90]: I'm not sure but is it correct to use borderWidth here? @plainheart

Comment (plainheart) [reply src/component/tooltip/TooltipHTMLContent.ts:90]: It may be not appropriate to use `borderWidth` as arrow size, but perhaps we can multiply it by a factor. And the calculated `arrowOffset` seems to be not accurate enough. Here is my humble opinion about the calculation,

```diff
 src/component/tooltip/TooltipHTMLContent.ts

@@ -73,22 +73,27 @@ function assembleArrow(
 
     borderColor = convertToColorString(borderColor);
     const arrowPos = mirrorPos(arrowPosition);
-    const arrowOffset = Math.round(Math.sqrt(2 * borderWidth * borderWidth) / 2) + borderWidth;
-    let positionStyle = `${arrowPos}:-${arrowOffset}px;`;
+    const arrowSize = Math.max(Math.round(borderWidth) * 1.5, 6);
+    let positionStyle = '';
     let transformStyle = CSS_TRANSFORM_VENDOR + ':';
+    let rotateDeg = 0;
     if (indexOf(['left', 'right'], arrowPos) > -1) {
         positionStyle += 'top:50%';
-        transformStyle += `translateY(-50%) rotate(${arrowPos === 'left' ? -225 : -45}deg)`;
+        transformStyle += `translateY(-50%) rotate(${rotateDeg = arrowPos === 'left' ? -225 : -45}deg)`;
     }
     else {
         positionStyle += 'left:50%';
-        transformStyle += `translateX(-50%) rotate(${arrowPos === 'top' ? 225 : 45}deg)`;
+        transformStyle += `translateX(-50%) rotate(${rotateDeg = arrowPos === 'top' ? 225 : 45}deg)`;
     }
+    const arrowOffset = Math.round((borderWidth * Math.SQRT2 + arrowSize / 2) * 100) / 100;
+    positionStyle += `;${arrowPos}:-${arrowOffset}px`;
+    const margin = Math.round(borderWidth / 2 * Math.abs(Math.cos(rotateDeg)) * 100) / 100;
 
     const borderStyle = `${borderColor} solid ${borderWidth}px;`;
     const styleCss = [
-        `position:absolute;width:${borderWidth}px;height:${borderWidth}px;`,
+        `position:absolute;width:${arrowSize}px;height:${arrowSize}px;`,
         `${positionStyle};${transformStyle};`,
+        `margin-${arrowPos}:${margin}px;`,
         `border-bottom:${borderStyle}`,
         `border-right:${borderStyle}`,
         `background-color:${backgroundColor};`

```

Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts:90]: Sure, these calculations seems more accurate. Thanks :)

Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts]: @plainheart I have addressed your comment. Thank you :)

Comment (plainheart) [reply src/component/tooltip/TooltipHTMLContent.ts]: @g7i Thanks for your work. But I think our current calculation is still not accurate enough. It needs to be improved.

Comment (g7i) [reply src/component/tooltip/TooltipHTMLContent.ts]: @plainheart I have replaced everything you suggested in the comment. Could you please tell me the cases where the calculation is getting off so that I can improve. Thank you...

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 10]
```diff
@@ -60,36 +60,45 @@ function mirrorPos(pos: string): string {
...
+    const backgroundColor = tooltipModel.get('backgroundColor');
+    const borderWidth = tooltipModel.get('borderWidth');
+
     borderColor = convertToColorString(borderColor);
     const arrowPos = mirrorPos(arrowPosition);
-    let positionStyle = `${arrowPos}:-6px;`;
+    const arrowSize = Math.max(Math.round(borderWidth) * 1.5, 6);
+    let positionStyle = '';
     let transformStyle = CSS_TRANSFORM_VENDOR + ':';
+    let rotateDeg = 0;
```
Comment (plainheart) [inline src/component/tooltip/TooltipHTMLContent.ts:79]:
```suggestion
    let rotateDeg;
```

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 11]
```diff
@@ -60,36 +60,45 @@ function mirrorPos(pos: string): string {
...
+        transformStyle += `translateY(-50%) rotate(${rotateDeg = arrowPos === 'left' ? -225 : -45}deg)`;
     }
     else {
         positionStyle += 'left:50%';
-        transformStyle += `translateX(-50%) rotate(${arrowPos === 'top' ? 225 : 45}deg)`;
+        transformStyle += `translateX(-50%) rotate(${rotateDeg = arrowPos === 'top' ? 225 : 45}deg)`;
     }
+    const arrowOffset = Math.round((borderWidth * Math.SQRT2 + arrowSize / 2) * 100) / 100;
+    positionStyle += `;${arrowPos}:-${arrowOffset}px`;
+    const margin = Math.round(borderWidth / 2 * Math.abs(Math.cos(rotateDeg)) * 100) / 100;
```
Comment (plainheart) [inline src/component/tooltip/TooltipHTMLContent.ts:90]:
```suggestion
```

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 12]
```diff
@@ -60,36 +60,45 @@ function mirrorPos(pos: string): string {
...
         positionStyle += 'top:50%';
-        transformStyle += `translateY(-50%) rotate(${arrowPos === 'left' ? -225 : -45}deg)`;
+        transformStyle += `translateY(-50%) rotate(${rotateDeg = arrowPos === 'left' ? -225 : -45}deg)`;
     }
     else {
         positionStyle += 'left:50%';
-        transformStyle += `translateX(-50%) rotate(${arrowPos === 'top' ? 225 : 45}deg)`;
+        transformStyle += `translateX(-50%) rotate(${rotateDeg = arrowPos === 'top' ? 225 : 45}deg)`;
     }
+    const arrowOffset = Math.round((borderWidth * Math.SQRT2 + arrowSize / 2) * 100) / 100;
```
Comment (plainheart) [inline src/component/tooltip/TooltipHTMLContent.ts:88]:
```suggestion
    const rotateRadian = rotateDeg * Math.PI / 180;
    const arrowWH = arrowSize + borderWidth;
    const rotatedWH = arrowWH * Math.abs(Math.cos(rotateRadian)) + arrowWH * Math.abs(Math.sin(rotateRadian));
    const arrowOffset = Math.round(((rotatedWH - Math.SQRT2 * borderWidth) / 2
        + Math.SQRT2 * borderWidth - (rotatedWH - arrowWH) / 2) * 100) / 100;
```

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 9 above)
Comment (plainheart) [reply src/component/tooltip/TooltipHTMLContent.ts]: @g7i You could use various `borderWidth` to test if the arrow will be off a bit.

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 13]
```diff
@@ -60,36 +60,45 @@ function mirrorPos(pos: string): string {
...
+    positionStyle += `;${arrowPos}:-${arrowOffset}px`;
+    const margin = Math.round(borderWidth / 2 * Math.abs(Math.cos(rotateDeg)) * 100) / 100;
 
-    const borderStyle = `${borderColor} solid 1px;`;
+    const borderStyle = `${borderColor} solid ${borderWidth}px;`;
     const styleCss = [
-        'position:absolute;width:10px;height:10px;',
+        `position:absolute;width:${arrowSize}px;height:${arrowSize}px;`,
         `${positionStyle};${transformStyle};`,
+        `margin-${arrowPos}:${margin}px;`,
```
Comment (plainheart) [inline src/component/tooltip/TooltipHTMLContent.ts:99]:
```suggestion
```

**Comment by g7i** [comment]
Thanks for helping me out :)

**Comment by plainheart** [comment]
@g7i Really thank you for the work!
@pissang Please help take a double check. I think it should be working well.

**Comment by g7i** [comment]
Is it ready to be merged now?

**Comment by plainheart** [comment]
> Is it ready to be merged now?

It looks good to me now. If other maintainers have no issue with this, it will be merged.

**Comment by g7i** [comment]
> > Is it ready to be merged now?
> 
> It looks good to me now. If other maintainers have no issue with this, it will be merged.

Alright, thanks :tada:

**Review by pissang — APPROVED** [review]

**Comment by pissang** [comment]
LGTM. @g7i Thanks for keeping improving your PR and @plainheart thanks for the detailed review.
