### PR TITLE
fix(visualmap): add textShadowColor, make text shadow work on visualMap. close #14440

### LINKED ISSUE #14440: Text shadow is not working on visualMap
### Version
5.0.1

### Reproduction link
[https://jsfiddle.net/x4Lf09tm/](https://jsfiddle.net/x4Lf09tm/)

### Steps to reproduce
Set the text shadow on visualMap:
```js
visualMap: {
  textStyle: {
    color: '#000',
    textShadowColor: '#000',
    textShadowBlur: 2,
  }
}
```

### What is expected?
The text has shadow on it.

### What is actually happening?
No shadow on the text.

### PR DESCRIPTION
**Pull request by fuchunhui**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Fix a bug that some text styles are not working on `visualMap`. 

### Fixed issues

- #14440

### visualMap-continuous

| Before | After |
| :----: | :----: |
| image | image |

### visualMap-piecewise

| Before | After |
| :----: | :----: |
| image | image |

## Misc
- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

- `test/visualMap-continuous.html`
- `test/visualMap-pieces.html`

### Merging options

- [x] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/component/visualMap/ContinuousView.ts [hunk 1]
```diff
@@ -191,7 +192,8 @@ class ContinuousView extends VisualMapView {
                 align: orient === 'horizontal' ? align as TextAlign : 'center',
                 text: text,
                 font: textStyleModel.getFont(),
-                fill: textStyleModel.getTextColor()
+                fill: textStyleModel.getTextColor(),
+                ...textShadow
```
Comment (plainheart) [inline src/component/visualMap/ContinuousView.ts:196]: If you hope more styles get applied, I think it may be better to use `createTextStyle` in `src/label/labelStyle.ts`.

Comment (fuchunhui) [reply src/component/visualMap/ContinuousView.ts:196]: you are right, `createTextStyle` is more powerful.

File: src/model/mixin/textStyle.ts [hunk 2]
```diff
@@ -77,6 +79,15 @@ class TextStyleMixin {
         tmpText.update();
         return tmpText.getBoundingRect();
     }
+
+    getTextShadow(this: Model<LabelTextShadowOption>) {
```
Comment (Ovilia) [inline src/model/mixin/textStyle.ts:83]: No longer needed.

**Review by Ovilia — CHANGES_REQUESTED** [review]

File: src/component/visualMap/ContinuousView.ts [hunk 3]
```diff
@@ -182,17 +183,19 @@ class ContinuousView extends VisualMapView {
...
                 y: position[1],
                 verticalAlign: orient === 'horizontal' ? 'middle' : align as TextVerticalAlign,
                 align: orient === 'horizontal' ? align as TextAlign : 'center',
-                text: text,
+                text,
                 font: textStyleModel.getFont(),
-                fill: textStyleModel.getTextColor()
-            }
+                fill: textStyleModel.getTextColor(),
+                ...textShadow
```
[the remark this answers is not in the document]
Comment (fuchunhui) [reply src/component/visualMap/ContinuousView.ts:197]: Great, find it. [labelStyle.ts#L559](https://github.com/apache/echarts/blob/9c0c99131adecdbdbe416a51553c36ce0569db50/src/label/labelStyle.ts#L559)

File: src/model/mixin/textStyle.ts (hunk 2 above)
Comment (fuchunhui) [reply src/model/mixin/textStyle.ts:83]: ok

**Review by plainheart — DISMISSED** [review]
LGTM

**Review by plainheart — COMMENTED** [review]
One more question,
Should we also apply text style to [`handleLabel`](https://github.com/apache/echarts/blob/764b5c8698519201ac565786c6f8c328e9c4c2af/src/component/visualMap/ContinuousView.ts#L618) and [`indicatorLabel`](https://github.com/apache/echarts/blob/764b5c8698519201ac565786c6f8c328e9c4c2af/src/component/visualMap/ContinuousView.ts#L359)?

**Review by Ovilia — APPROVED** [review]
LGTM

**Comment by fuchunhui** [comment]
@plainheart Your editing is great, more smarter.

**Comment by pissang** [comment]
> Should we also apply the text style on [handleLabel](https://github.com/apache/echarts/blob/764b5c8698519201ac565786c6f8c328e9c4c2af/src/component/visualMap/ContinuousView.ts#L618) and [indicatorLabel](https://github.com/apache/echarts/blob/764b5c8698519201ac565786c6f8c328e9c4c2af/src/component/visualMap/ContinuousView.ts#L359)?

@fuchunhui @plainheart So are we planning to add this in this PR?

**Review by plainheart — APPROVED** [review]
LGTM

**Review by pissang — APPROVED** [review]
