### PR TITLE
fix(scatter): fix jitter layout does not support progressive rendering and cause chart to freeze and potential NPE

### LINKED ISSUE #21434: [Bug] Performance regression for large data set after updating to v6
### Version

6.0.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=scatter-large

### Steps to Reproduce

Open the Large Scatter example on the example page.

### Current Behavior

The browser hangs and CPU usage spike to 100% when interact (zooming, panning...) with the plot.

### Expected Behavior

CPU usage stays low, and interacting with the plot feels smooth.

The same example performs much better in v5 compared to v6, which can even be seen on [Wayback Machine](https://web.archive.org/web/20250319095206/https://echarts.apache.org/examples/en/editor.html?c=scatter-large) before v6 was introduced this July.

### Environment

```markdown
- OS: Windows 11 25H2
- Browser: Chrome 143.0.7499.109
- Framework: None
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by plainheart**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Current implementation of `scatterJitterLayout` does not support progressive rendering like [`scatterPointsLayout`](https://github.com/apache/echarts/blob/bbe3591a8a946b62a16e2ee6e254d8d1ed0c2741/src/layout/points.ts#L85-L88), which causes two issues:

1. Chart freezes with large datasets
2. Chart throws NPE with progressive rendering as the layout points use typed array and can not be retrieved by `seriesData.getItemLayout(idx)`

Please take a look at [this online example](https://echarts.apache.org/examples/editor.html?c=scatter-large) for a quick view. 

### Fixed issues

- Resolves #21434

## Comparison

image

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### Security Checking

- [ ] This PR uses security-sensitive Web APIs.

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

- The 4th/5th test cases in `test/scatter-jitter.html`.
- `test/scatter-weibo.html`
- `test/scatter-stream-large.html`
- `test/scatter-random-stream.html`

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/util/jitter.ts [hunk 1]
```diff
@@ -67,21 +67,19 @@ export function fixJitter(
...
-            return fixJitterIgnoreOverlaps(floatCoord, jitter, bandWidth, radius);
-        }
-        else {
-            return fixJitterAvoidOverlaps(fixedAxis, fixedCoord, floatCoord, radius, jitter, jitterMargin);
-        }
+    if (jitterOverlap) {
+        return fixJitterIgnoreOverlaps(floatCoord, jitter, bandWidth, radius);
     }
-    return floatCoord;
+    return fixJitterAvoidOverlaps(fixedAxis, fixedCoord, floatCoord, radius, jitter, jitterMargin);
```
Comment (plainheart) [inline src/util/jitter.ts:82]: No logical bug here. Just tweaked the code style.
