### PR TITLE
fix(toolbox): fix dataView component does not fit dark mode

### LINKED ISSUE #21170: [Bug] toolbox data view not compatible with dark theme
### Version

6.0.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-marker

### Steps to Reproduce

1. init -> echarts.init(chartDom, 'dark')

2.  setOption ->  toolbox: { dataView: { show: true }  }

### Current Behavior

Image

### Expected Behavior

The expected style should be dark

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by notthistrain**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Fix the DataView component does not fit dark mode.

### Fixed issues

- Fix #21170

### Before: What was the problem?

Create an instance of the dark theme, but the style of the dataview is not dark

image

### After: How does it behave after the fixing?

The style of dataview follows the theme

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### Other information

### CODE REVIEW

File: src/theme/dark.ts [hunk 1]
```diff
@@ -103,6 +103,16 @@ const theme = {
     toolbox: {
         iconStyle: {
             borderColor: color.accent50
+        },
+        feature: {
+            dataView: {
+                backgroundColor: color.background,
```
Comment (plainheart) [inline src/theme/dark.ts]: Can reuse the `background` constant that was declared at line 23.

```suggestion
                backgroundColor: backgroundColor,
```

And please @Ovilia review if the proposed dark colors for the toolbox are suitable.

Comment (notthistrain) [reply src/theme/dark.ts]: Thank you for your time. I have made the suggested modifications

**Comment by Ovilia** [comment]
Thanks for your contribution!
