### PR TITLE
Fix(sankey): sankey label has higher z2

### LINKED ISSUE #14287: ECharts Sankey: Labels are hidden under lines with line emphasis
### Version
5.0.0

### Reproduction link
[https://jsfiddle.net/ed6cq5yj/1/](https://jsfiddle.net/ed6cq5yj/1/)

### Steps to reproduce
Once loaded, hover over the link between node1 and node2;
The label for node2 will be partially obscured by the emphasized link.

### What is expected?
The label should remain above the link.

### What is actually happening?
The label is partially cut off.

---
If this is intended behaviour, it would be nice to have an option to force labels to render above lines on emphasis.

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Set `sankey label`  z2 property.

### Fixed issues

Close #14287 

### Before: What was the problem?
Screen Shot 2021-03-07 at 22 56 11

### After: How is it fixed in this PR?

Screen Shot 2021-03-07 at 22 55 57

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

`sankey-vertical.html`

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

**Review by pissang — APPROVED** [review]

File: src/chart/sankey/SankeyView.ts [hunk 1]
```diff
@@ -250,7 +250,8 @@ class SankeyView extends ChartView {
                     width: layout.dx,
                     height: layout.dy
                 },
-                style: itemModel.getModel('itemStyle').getItemStyle()
+                style: itemModel.getModel('itemStyle').getItemStyle(),
+                z2: 10
```
Comment (plainheart) [inline src/chart/sankey/SankeyView.ts:254]: @pissang @susiwen8  Sorry here. I ever reverted it in #14542. But for now, this change seems to be still needed?

Comment (pissang) [reply src/chart/sankey/SankeyView.ts:254]: @plainheart Seems so, do you mind adding it before we vote for this release?

Comment (plainheart) [reply src/chart/sankey/SankeyView.ts:254]: Sure. It's here. #14640
