### PR TITLE
fix(BarView): borderColor hides bar color with large data. close #18185

### LINKED ISSUE #18185: [Bug] borderColor hides bar color with large data
### Version

5.4.1

### Link to Minimal Reproduction

_No response_

### Steps to Reproduce

I don't know if in version 5.2.1 It was the good result , but when I add `borderColor` property in ìtemStyle` (series), the color is not visible with large data, in 5.4.1 yes. So it hides the color of the bars.
```
    {
      name: 'Volumn',
      type: 'bar',
      xAxisIndex: 1,
      yAxisIndex: 1,
      itemStyle: {
        color: '#7fbe9e',
        // Add black color...
        borderColor: 'black'
      },
      large: true,
      encode: {
        x: 0,
        y: 5
      }
    }
```

### Current Behavior

In [5.4.1](https://echarts.apache.org/examples/en/editor.html?c=candlestick-large&code=MYewdgzgLgBArgBwMIgDYgE4wLwwOQDEApsAAzml4DcAUKJLIgEKYAmRGK6WuhAHAEEKlWvWgxWIAO5gumHPgLlWAQwDMwanXDjJMlhnac083ktJ8AYgCY-WsbFVQVKOGFi5rRAKyidjlWcFAHMiMA5AogB5AAkAGSQACicXEDcoAEpaEAQoAEtwBQBvGhgJQJUIIigALhgSsrKINIxgIjqU0pgAXwAaLvyoVHb6rrKoIgAPWvwAEQqYAQBbNPc6vBgAahgSAAsVDCgIADoAM0wlwOOVVlYUJcuIZIrXdwyuvoGQNHyEOobGlAMHlgqEMOsVJM8hA8P1GjBIdCAAogPLuDj_MaAgCeCBGeFQaKIeCx3Q-cJgUG-qAARiBJpj4aciIE4BgRgD4SkAFrfJaM-GNbECKEQACSYHYDJgpxUqCqWLKZPhyp6FOCwNYdQA2ljOY1hqcZngAIykACksMVMGBwV2xrNlop8LpUCp_Jg1nIpOdo0FMENDotVv9tvt60dIcFuyIIPDMD4pF9ZVd7rqidJXQAuhTJiLoTq9daoLj8cBIsFMNioy7VqoMNiAOIqP4yuVVZMwAD0XZgaIAbhwqnUgXAiJ3ERA4kT_jBwNyOCA6rL5UQ1daIAhCVBp-FZxBdtJl-2159_Us0esUgBZNE1xqXaV4G-Qkkq3368al9bliaVhv3mUGp5KwEpSnUJqdnSbj1k2LbHquE6iruHJzmAC4YEubaruu_qTgAKnkwAANb7oeUgIVUuGCpu24oWRR7YVRZ6CpOcQqDSRCoAxFFMaenYXmAV4VLeYCATAj7Cc416vpmZQ5l0wqioW8KfjAEDlsMI4YGOna0XkUACOyKgCv6B6MaORDWqqSofhumkjJZnbAaBkpTBBelbgZABycBLJx4Kekh0LsZx3H1Op5GUfx1psTOEXmbxK7McFECESRPHRdR8L6Tu8VFJFjHJaeckwApZQ8nyKmNGpJZ4usaIQCBxKdnmopge5MDakmMAmuVNHOIcEFJtaYRar13rvkWZlRZSOnjtabXQh10rdb0vX9fCdX4hAhJGOJqYgB6Zp6YNMwnaNkrDaQpX9f20JwHKMmtvqiXRb6VTAkQ4pudKkFYqweRLGETXgHUABsvoIHkJDfdVqnWmU_ZymOHmIzAoDcHUiByBg1mdmpSMoyMAC0_3-mUmOYB00iyCYeP-jZZXkl0n0wxA8N-oK20_iokrDNARHEeJBlEEsADKJZaVz_pU4FOP052lP06QNMyLjSswHShgcLj2MIAYRga-j2tGyratgIbuv0_jl2gOwpmCtKI0UzA2I6pBMAACzrWo63WFm1k-tNgpgCowPrAAamgfliZ2PP4DSBziUtP3gb1nZKctv1o_6osS1LHLo3L6wEAA7KcnEAJwtSbbDW1jieoCoJHiSx8LNxgoTabpdsgA7MtO3ULsU-7MDeEHKrZjQ3S0KcbjAPkhShOEGCRLECSJKA6QZFzwwBEEuDalmtBlPvMCTJHxMKJs4RSDA8wTIkXomp7PUmlkXTn4JcATAo4OkBgAAKgmuQU-AZqha0qEQK-qAxwKBklAXYxw16SiOokXeICTRejAV_SBdJL7tgUHfRYGA17YkSF7T-Z9IGqGxAAJT5qEBQ2DwHnCwIkc-eQFCkCoH2GAAAeDGqwoB8LyJsTYu99RJyqLA-BuAZEwOvtsRByDUGSCWBg4BnpAEkwmuAso7CYCcMgQAKx4Xw8xQivaWIkVI60BDYEQG1KYrMChEiqJQXzDRWi9GkGON4TB5QGFMLXNsRRciiAGJ6FiRx7ZjjNEOBg6J58chhDFKwSYCDAhqLrB4nJXi0GaKCWoahBpIHAHQFUDJWTcCeMwjBfJSDCk-KCdYMpZQ8inGMZUkA1TMk4GwLgNJYAan2NllUogNSJHRKZuffsMclhgAUHE-U2o1BuJAYkM05AtgwHqd49BQTvDkA6d2Xs2o8AjNhPgXpVQbkEmkN9KADzdhxmeQ8hZcCll4EDvCHsXVPY-xgH7T0fzGgpG1HkNxR9RrAH2IcE47DLhQDOBcQIhFgaJDwNiXF2ISbXmvCTW4AAdMAuxdg1AeDUCAMJ1qJEIXAsJuAf4TAyBkTsmxVnOJGTUrMxwqSWDyJMIgrBn4cutFy-kTj1n8sFcK0V4rOXcu6nKkAQqRVivacq6V7ZtR3KmZktVGrFXaslV82OAr1UKrFaQCV_pQhQHFiCMAzxnDrTyOtKVjKeV4lGUar1KqDV8vWlQ856kXVYhPh8Lo7IoBsmWSkNhC8l7LMdc64IrqUjrRSCtdaIzYHrQNYWjGkzZhAzGYPZGWAmqZuiV04xBa5QwAAHylr6Uo1A4yaIuoUGTWZOwcINsSE21Agj22yLlN2nKvbcAmgHVxKiala3LOwOjXNv1W0wBuq7MoAB-cNYpukGsGcMv1RajoIAOGuKQBldgTrXCAbpzdxDslAIYdGXIKjag3VKGAei-r6rLRWo1gjcDFrlJ-xoB6TRQbKHUMmUG6gAu8iAG0JA2Bzm6Qgdk900gQHWlUWAVItZrgQH0gyeRBxwd6rMrEcaE0RrrTG7oQA
)

### Expected Behavior

The good result for me in [5.2.1](https://echarts.apache.org/examples/en/editor.html?c=candlestick-large&version=5.2.1&code=MYewdgzgLgBArgBwMIgDYgE4wLwwOQDEApsAAzml4DcAUKJLIgEKYAmRGK6WuhAHAEEKlWvWgxWIAO5gumHPgLlWAQwDMwanXDjJMlhnac083ktJ8AYgCY-WsbFVQVKOGFi5rRAKyidjlWcFAHMiMA5AogB5AAkAGSQACicXEDcoAEpaEAQoAEtwBQBvGhgJQJUIIigALhgSsrKINIxgIjqU0pgAXwAaLvyoVHb6rrKoIgAPWvwAEQqYAQBbNPc6vBgAahgSAAsVDCgIADoAM0wlwOOVVlYUJcuIZIrXdwyuvoGQNHyEOobGlAMHlgqEMOsVJM8hA8P1GjBIdCAAogPLuDj_MaAgCeCBGeFQaKIeCx3Q-cJgUG-qAARiBJpj4aciIE4BgRgD4SkAFrfJaM-GNbECKEQACSYHYDJgpxUqCqWLKZPhyp6FOCwNYdQA2ljOY1hqcZngAIykACksMVMGBwV2xrNlop8LpUCp_Jg1nIpOdo0FMENDotVv9tvt60dIcFuyIIPDMD4pF9ZVd7rqidJXQAuhTJiLoTq9daoLj8cBIsFMNioy7VqoMNiAOIqP4yuVVZMwAD0XZgaIAbhwqnUgXAiJ3ERA4kT_jBwNyOCA6rL5UQ1daIAhCVBp-FZxBdtJl-2159_Us0esUgBZNE1xqXaV4G-Qkkq3368al9bliaVhv3mUGp5KwEpSnUJqdnSbj1k2LbHquE6iruHJzmAC4YEubaruu_qTgAKnkwAANb7oeUgIVUuGCpu24oWRR7YVRZ6CpOcQqDSRCoAxFFMaenYXmAV4VLeYCATAj7Cc416vpmZQ5l0wqioW8KfjAEDlsMI4YGOna0XkUACOyKgCv6B6MaORDWqqSofhumkjJZnbAaBkpTBBelbgZABycBLJx4Kekh0LsZx3H1Op5GUfx1psTOEXmbxK7McFECESRPHRdR8L6Tu8VFJFjHJaeckwApZQ8nyKmNGpJZ4usaIQCBxKdnmopge5MDakmMAmuVNHOIcEFJtaYRar13rvkWZlRZSOnjtabXQh10rdb0vX9fCdX4hAhJGOJqYgB6Zp6YNMwnaNkrDaQpX9f20JwHKMmtvqiXRb6VTAkQ4pudKkFYqweRLGETXgHUABsvoIHkJDfdVqnWmU_ZymOHmIzAoDcHUiByBg1mdmpSMoyMAC0_3-mUmOYB00iyCYeP-jZZXkl0n0wxA8N-oK20_iokrDNARHEeJBlEEsADKJZaVz_pU4FOP052lP06QNMyLjSswHShgcLj2MIAYRga-j2tGyratgIbuv0_jl2gOwpmCtKI0UzA2I6pBMAACzrWo63WFm1k-tNgpgCowPrAAamgfliZ2PP4DSBziUtP3gb1nZKctv1o_6osS1LHLo3L6wEAA7KcnEAJwtSbbDW1jieoCoJHiSx8LNxgoTabpdsgA7MtO3ULsU-7MDeEHKrZjQ3S0KcbjAPkhShOEGCRLECSJKA6QZFzwwBEEuDalmtBlPvMCTJHxMKJs4RSDA8wTIkXomp7PUmlkXTn4JcATAo4OkBgAAKgmuQU-AZqha0qEQK-qAxwKBklAXYxw16SiOokXeICTRejAV_SBdJL7tgUHfRYGA17YkSF7T-Z9IGqGxAAJT5qEBQ2DwHnCwIkc-eQFCkCoH2GAAAeDGqwoB8LyJsTYu99RJyqLA-BuAZEwOvtsRByDUGSCWBg4BnpAEkwmuAso7CYCcMgQAKx4Xw8xQivaWIkVI60BDYEQG1KYrMChEiqJQXzDRWi9GkGON4TB5QGFMLXNsRRciiAGJ6FiRx7ZjjNEOBg6J58chhDFKwSYCDAhqLrB4nJXi0GaKCWoahBpIHAHQFUDJWTcCeMwjBfJSDCk-KCdYMpZQ8inGMZUkA1TMk4GwLgNJYAan2NllUogNSJHRKZuffsMclhgAUHE-U2o1BuJAYkM05AtgwHqd49BQTvDkA6d2Xs2o8AjNhPgXpVQbkEmkN9KADzdhxmeQ8hZcCll4EDvCHsXVPY-xgH7T0fzGgpG1HkNxR9RrAH2IcE47DLhQDOBcQIhFgaJDwNiXF2ISbXmvCTW4AAdMAuxdg1AeDUCAMJ1qJEIXAsJuAf4TAyBkTsmxVnOJGTUrMxwqSWDyJMIgrBn4cutFy-kTj1n8sFcK0V4rOXcu6nKkAQqRVivacq6V7ZtR3KmZktVGrFXaslV82OAr1UKrFaQCV_pQhQHFiCMAzxnDrTyOtKVjKeV4lGUar1KqDV8vWlQ856kXVYhPh8Lo7IoBsmWSkNhC8l7LMdc64IrqUjrRSCtdaIzYHrQNYWjGkzZhAzGYPZGWAmqZuiV04xBa5QwAAHylr6Uo1A4yaIuoUGTWZOwcINsSE21Agj22yLlN2nKvbcAmgHVxKiala3LOwOjXNv1W0wBuq7MoAB-cNYpukGsGcMv1RajoIAOGuKQBldgTrXCAbpzdxDslAIYdGXIKjag3VKGAei-r6rLRWo1gjcDFrlJ-xoB6TRQbKHUMmUG6gAu8iAG0JA2Bzm6Qgdk900gQHWlUWAVItZrgQH0gyeRBxwd6rMrEcaE0RrrTG7oQA)

### Environment

```markdown
- OS: macOS Ventura
- Browser: Safari 16.1
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by DevitX**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### Fixed issues

- #18185: ...

### Before: What was the problem?

borderColor in itemStyle overrides the color of Bar series on large data
image
image

### After: How does it behave after the fixing?

reset color to default one.
image
image

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### New Test Output

image

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Review by Ovilia — COMMENTED** [review]
I'm not sure about if we should change like this. Is it expected to show fill color instead of stroke color in large scale bars? A reason to say NO for me is that the stoke width is a fixed width (etc. 1px) while the bar width is relatively quite small when in large scale bars, far less than 1px. So I would prefer to expect showing border color in this case.

**Comment by DevitX** [comment]
> I'm not sure about if we should change like this. Is it expected to show fill color instead of stroke color in large scale bars? A reason to say NO for me is that the stoke width is a fixed width (etc. 1px) while the bar width is relatively quite small when in large scale bars, far less than 1px. So I would prefer to expect showing border color in this case.

Hi @Ovilia, thank you for your review! I believe that the expected behavior for a user is that: changing the border color should only affect the border even in large data, resulting in a bar with a distinct inner color and outer border. However in this case, since that is not possibile (like you said for very small width) with larger datasets, you end up with a single color and that can be quite messy. In this example: applying a black border:
image

A possible solution might be to ignore user-defined colors at high data density, displaying the chart as if no borderColor is specified. This would revert to a simpler, default color scheme for clarity. And on zoom to less dense data, apply the correct property. What do you think about this? The default color is this:
image

@nico-robert what behavior did you expect?

**Comment by nico-robert** [comment]
> @nico-robert what behavior did you expect?

For me (personal opinion), the correct behavior is the result obtained with version 5.2.1, i.e. a border color that doesn't conflict with the color of the bar when the zoom is large and data is important.
I don't know if it's difficult, but why not go back to the settings of version 5.2.1 ?

File: src/chart/bar/BarView.ts [hunk 1]
```diff
@@ -1176,7 +1176,8 @@ function createLarge(
     el.barWidth = barWidth;
     group.add(el);
     el.useStyle(data.getVisual('style'));
-
+    // Reset stroke color
+    el.style.stroke = null;
```
Comment (Ovilia) [inline src/chart/bar/BarView.ts:1180]: Setting stroke to be null is not acceptable because users can set `largeThreshold` to a very small number like 10 and large rendering will be used even if the bar-width much more wider than 1px. In this case, setting stroke to be null is not expected.

Comment (Ovilia) [reply src/chart/bar/BarView.ts:1180]: `el.style.strokeFirst = true;` makes sure stroking is rendered before filling so that filling colors will not be overlapped by stoking. The result is as follows:

image

The filling color is blue and the stroking color is red in the above case.

If this is expected result, you may update your PR like that.

Here's the test option:

```js
var xAxisData = [];
var data1 = [];
for (var i = 0; i < 10000; i++) {
    xAxisData.push('类目' + i);
    data1.push((Math.random() * 5).toFixed(2));
}

var option = {
    legend: {
        data: ['bar'],
        align: 'left'
    },
    tooltip: {},
    dataZoom: [{
        start: 30,
        end: 100,
        type: 'slider'
    }],
    xAxis: {
        data: xAxisData,
        silent: false,
        splitLine: {
            show: false
        },
        splitArea: {
            show: false
        }
    },
    yAxis: {
        splitArea: {
            show: false
        }
    },
    series: [{
        name: 'bar',
        type: 'bar',
        large: true,
        largeThreshold: 10,
        data: data1,
        itemStyle: {
            borderWidth: 1,
            borderColor: 'red'
        }
    }]
}
```

**Review by Ovilia — CHANGES_REQUESTED** [review]

File: src/chart/bar/BarView.ts (hunk 1 above)
Comment (DevitX) [reply src/chart/bar/BarView.ts:1180]: Thanks @Ovilia! I updated my code based on your review, and your solution resolved the issue. The only thing I noticed is that, in a larger chart there seems to be a darker area. I suspect this might be caused by overlapping bars, but I'm not really sure if it’s an actual problem. Have you encountered something like this in your environment?
(I use a 1920x1080 monitor and used the option that you  provided)

Have a great day!

image

Comment (Ovilia) [reply src/chart/bar/BarView.ts]: The part inside yellow windows seems to be correct but the ones having redish shadow don't seem quite right. I will have a double check with other committers. Thanks for letting me know!

Comment (Ovilia) [reply src/chart/bar/BarView.ts]: I checked the SVG of rendered path, and it seemed to be all right. Maybe it's a problem of SVG/Canvas implementation. After discussing with others, we would suggest setting `stroke = null` as you did in the previous commit. Sorry for your time!

Comment (DevitX) [reply src/chart/bar/BarView.ts]: > I checked the SVG of rendered path, and it seemed to be all right. Maybe it's a problem of SVG/Canvas implementation. After discussing with others, we would suggest setting `stroke = null` as you did in the previous commit. Sorry for your time!

Thank you, I will try to see if I can find a better solution in general. No worries =)

Comment (DevitX) [reply src/chart/bar/BarView.ts]: I tried but I didn't find a better solution. I remodified the file to reinclude 
`el.style.stroke = null;` in place of `el.style.strokeFirst = true;`

**Review by Ovilia — APPROVED** [review]

**Review by Ovilia — APPROVED** [review]
