### PR TITLE
fix(line): using sampling with lttb, NaN point should not be filtered. 

### LINKED ISSUE #14689: Using sampling with connectNulls connects regular datapoints with null ones when zoomed out
### Version
5.1.0

### Reproduction link
~[https://codepen.io/tmscer/pen/wvgxKNR](https://codepen.io/tmscer/pen/wvgxKNR)~
[https://codepen.io/tmscer/pen/yLgGXbo](https://codepen.io/tmscer/pen/yLgGXbo)

### Steps to reproduce
Use a series line with `connectNulls: false` and `sampling: 'lttb'` (may be reproducible with other sampling methods) and have a null value in your data.

### What is expected?
I'd expect null values to never be connected with regular values.

### What is actually happening?
When zoomed out, regular values are connected with null values. When zoomed in, the line between regular values and nulls disappears and behaves as expected.

---
I suspect this may be caused by the sampling algorithm since when no sampling is used, null values are never connected with regular ones.

I'm not sure what version of Echarts is used in the codepen, however, the bug is reproducible in 5.1.0. To see the bug, zoom in the flat line. At the end of it, there is a null.

### PR DESCRIPTION
**Pull request by fuchunhui**
…. close #14689

## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### After: How is it fixed in this PR?

store NaN point, append first to every bucket, adjust Uint Array length.

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/data/DataStore.ts [hunk 1]
```diff
@@ -983,6 +985,10 @@ class DataStore {
                 }
             }
 
+            if (appendNaNList.length && appendNaNList.length !== frameEnd - frameStart) {
+                newIndices[sampledIndex++] = appendNaNList[0]; // append first NaN point in every bucket
```
Comment (pissang) [inline src/data/DataStore.ts:989]: If we only append the first NaN point. We should use a variable instead of an array because array will cost more. For example:

```ts
let firstNaNIndex = -1;

if (isNaN(y) && firstNaNIndex < 0) {
  firstNaNIndex = rawIndex.
)
...
if (firstNaNIndex >= 0) {
  newIndices[sampledIndex++] = firstNaNIndex;
}
```

The performance is one of the most important indicator when implementing the sampling algorithm. We can check if it's degenerated in the `test/sample-compare.html` case

**Review by pissang — CHANGES_REQUESTED** [review]

File: src/data/DataStore.ts (hunk 1 above)
Comment (fuchunhui) [reply src/data/DataStore.ts:989]: yes, got it.

File: src/data/DataStore.ts [hunk 2]
```diff
@@ -983,6 +990,10 @@ class DataStore {
                 }
             }
 
+            if (countNaN > 0 && countNaN < frameEnd - frameStart) {
```
Comment (pissang) [inline src/data/DataStore.ts:993]: I'm not sure what's this `countNaN < frameEnd - frameStart` check for?

Comment (fuchunhui) [reply src/data/DataStore.ts:993]: In a bucket, if all data is NaN, execute the original logic without separate processing. `countNaN < frameEnd - frameStart` can avoid adding multiple times.

```
// set frameSize = 3；
const dimStore = [11, 22, 20, 33, 44, 55]; 
// IF result index is [1, 5]
```

Demo 1:
```
const dimStore = [null, 22, 20, 33, 44, 55]; 
// result index is [0, 1, 5]
```

Demo 2:
```
const dimStore = [null, null, null, 33, 44, 55]; 
// result index is [0, 5]
// if not check, result will become [0, 0, 5].
```

File: src/data/DataStore.ts [hunk 3]
```diff
@@ -991,7 +1002,12 @@ class DataStore {
         // First frame use the last data.
         newIndices[sampledIndex++] = this.getRawIndex(len - 1);
         target._count = sampledIndex;
-        target._indices = newIndices;
+
+        const _newIndices = new (getIndicesCtor(this._rawCount))(sampledIndex);
+        for (let idx = 0; idx < sampledIndex; idx++) {
+            _newIndices[idx] = newIndices[idx];
+        }
+        target._indices = _newIndices;
```
Comment (pissang) [inline src/data/DataStore.ts:1010]: It's not required to create a new array which match lenght precisely.

Instead of `_indices.length`, we use `_count` to indicate the length of indices. So we can avoid creating dynamic arrays that may has worse performance than a static array.

In the code, we don't need to create a `_newIndices`. Just use the `newIndices`, it's fine even if it has empty items.

File: src/data/DataStore.ts [hunk 4]
```diff
@@ -935,7 +935,7 @@ class DataStore {
         let area;
         let nextRawIndex;
 
-        const newIndices = new (getIndicesCtor(this._rawCount))(Math.ceil(len / frameSize) + 2);
+        const newIndices = new (getIndicesCtor(this._rawCount))(len);
```
Comment (pissang) [inline src/data/DataStore.ts:938]: Using `len` as estimated size is simple and safe, but not with best performance. From current strategy, we can know we may have at most two values in each frame(one for picked value and one for NaN value). And we use `Math.ceil(len / frameSize) + 2` to calculate the possible frames.

So following code will be more performant and also robust enough to calculate possible size when we having millions of data:
```ts
Math.min((Math.ceil(len / frameSize) + 2) * 2, len)
```

Comment (fuchunhui) [reply src/data/DataStore.ts:938]: good idea

File: src/data/DataStore.ts (hunk 3 above)
Comment (fuchunhui) [reply src/data/DataStore.ts:1010]: got it.

**Comment by pissang** [comment]
I'm not sure but when I'm running visual regression test(which has roslution 830x750), the current behavior seems to having unexpected points in the null values.

Before:
image

After:
image

**Comment by pissang** [comment]
I'm not sure if the behavior I described above is because we append both the NaN value and normal value. What if we only append the NaN value if there is any NaN value exists in one frame.

**Comment by fuchunhui** [comment]
> Seems when I'm running visual regression test(which has roslution 830x750), the current behavior seems to having unexpected points in the null values.
> 
> Before	After
> image	image
> image
> 
> Also I think we can add the case from https://codepen.io/tmscer/pen/yLgGXbo directly.

fixed. Due to incorrect index order.

**Comment by fuchunhui** [comment]
```
// set frameSize = 3；
const dimStore = [21, 22, 20, 33, 44, 55]; 
// IF result index is [1, 5]
```
Demo 1： 
```
const dimStore = [21, null, 20, 33, 44, 55]; 
// Right result is [0, 1, 5]
// Before, it would be [1, 0, 5], not right, this made the wrong case as you mentioned
```
@pissang

File: src/data/DataStore.ts [hunk 5]
```diff
@@ -983,6 +990,13 @@ class DataStore {
                 }
             }
 
+            if (countNaN > 0 && countNaN < frameEnd - frameStart) {
+                // Append first NaN point in every bucket.
+                // It is necessary to ensure the correct order of indices.
+                newIndices[sampledIndex++] = Math.min(firstNaNIndex, nextRawIndex);
+                nextRawIndex = Math.max(firstNaNIndex, nextRawIndex);
```
Comment (pissang) [inline src/data/DataStore.ts:997]: This may lead to append two `NaN` values because `nextRawIndex` is same with firstNaNIndex when it's smaller.

A possibly better solution is 
```ts
firstNaNIndex > nextRawIndex && (newIndices[sampledIndex++] = nextRawIndex);

if (countNaN > 0 && countNaN < frameEnd - frameStart) {
  newIndices[sampledIndex++] = Math.min(firstNaNIndex, nextRawIndex);
}
// Includes the case there is no NaN value, the firstNaNIndex is -1.
firstNaNIndex <= nextRawIndex && (newIndices[sampledIndex++] = nextRawIndex);
```

**Review by pissang — CHANGES_REQUESTED** [review]

**Review by pissang — APPROVED** [review]
