### PR TITLE
fix(tooltip): fix style coord transform markers are not removed after the tooltip is disposed

### LINKED ISSUE #19998: [Bug] Tooltip coordinate markers created by "makeStyleCoord" are not disposed
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MpxdiRtJGDAwP6QIG5xjCDU0AJywHQARsAC3KGDdgDcQA

### Steps to Reproduce

1. Set the `tooltip` to append to the `body`
2. The tooltip will create these "marker points" inside the `makeStyleCoord` function
3. These elements will be appended to the body
4. Dispose the chart

### Current Behavior

When the chart is disposed (and thus the tooltip is disposed), these marker elements are not removed from the DOM. This is kind of unexpected in a SPA, where the whole component is destroyed.
image

### Expected Behavior

These elements should not remain cached when all charts (we currently have a single one) are disposed.

### Environment

```markdown
- OS: Windows 11
- Browser: Chrome 125.0.6422.114
- Framework: Angular@17
```

### Any additional comments?

It's not that big of a deal since these are hidden, 0x0 elements, but still, unnecessary 4 elements in the DOM.

### PR DESCRIPTION
**Pull request by plainheart**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Fix the markers created by local coord transformer are not removed after the tooltip componet is disposed.

Related ZRender issue: ecomfe/zrender#1120

### Fixed issues

- Resolves #19998

### Before: What was the problem?

The markers won't be removed even if the chart is disposed.

image

### After: How does it behave after the fixing?

Clean up the markers when the tooltip component is disposed.

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

See any test cases about tooltip with `appendTo` or `appendToBody` specified.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 1]
```diff
@@ -307,7 +308,9 @@ class TooltipHTMLContent {
                     : isFunction(appendTo) && appendTo(api.getDom())
         );
 
-        makeStyleCoord(this._styleCoord, zr, container, api.getWidth() / 2, api.getHeight() / 2);
+        this._clearStyleCoord = makeStyleCoord(
+            this._styleCoord, zr, container, api.getWidth() / 2, api.getHeight() / 2
+        );
```
Comment (100pah) [inline src/component/tooltip/TooltipHTMLContent.ts:313]: `makeStyleCoord` is called twice in this file, and each call return a `clean` function. 
But only the last one is called when `dispose`. 
That still works because the two call of `makeStyleCoord` use the same input `zr` and `container`, but that dependency is not explicit in the API design a little bit.

It's OK to do it like that, but currently I think a better way might be:

Do not change `makeStyleCoord`.
And a new API: `transformLocalCoordClear` in `zrender/src/core/dom.ts`
And in `TooltipHTMLContainer.ts`:
```ts
dispose() {
    const zr = this._zr;
    transformLocalCoordClear(zr && zr.painter && zr.painter.getViewportRoot(), this._container);
    // ...
}
```

**Review by 100pah — CHANGES_REQUESTED** [review]

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 1 above)
Comment (plainheart) [reply src/component/tooltip/TooltipHTMLContent.ts:313]: This way looks much clear!

**Review by 100pah — APPROVED** [review]
