### PR TITLE
fix(dataZoom): render data not equally distributed. close #16924 #15921

### LINKED ISSUE #16924: [Bug] dataZoom data shadow line does not match with serie line
### Version

5.3.2

### Link to Minimal Reproduction

_No response_

### Steps to Reproduce

1. Goto https://echarts.apache.org/examples/en/editor.html
2. Enter code:

```javascript

const data = [
  [1650508472000,0],[1650508502000,0],[1650508532000,0],[1650508565000,0],
  [1650508596000,0],[1650508606000,0],[1650508626000,0],[1650508656000,0],
  [1650508686000,0],[1650508717000,0],[1650508772000,0],[1650508803000,0],
  [1650508833000,0],[1650508863000,0],[1650508893000,0],[1650508906000,0],
  [1650508923000,0],[1650508953000,0],[1650508985000,0],[1650509019000,0],
  [1650509071000,0],[1650509101000,0],[1650509132000,0],[1650509162000,0],
  [1650509194000,0],[1650509206000,0],[1650509224000,0],[1650509256000,0],
  [1650509286000,0],[1650509318000,0],[1650509373000,0],[1650509403000,0],
  [1650509433000,0],[1650509464000,0],[1650509494000,0],[1650509506000,0],
  [1650509524000,0],[1650509554000,0],[1650509586000,0],[1650509616000,0],
  [1650509672000,0],[1650509702000,0],[1650509734000,0],[1650509763000,0],
  [1650509794000,0],[1650509806000,0],[1650509824000,0],[1650509854000,0],
  [1650509884000,0],[1650509915000,0],[1650509973000,0],[1650510004000,0],
  [1650510034000,0],[1650510064000,0],[1650510095000,0],[1650510106000,0],
  [1650510125000,0],[1650510155000,0],[1650510185000,0],[1650510216000,0],
  [1650510271000,0],[1650510301000,0],[1650510333000,0],[1650510365000,0],
  [1650510395000,0],[1650510407000,0],[1650510425000,0],[1650510456000,0],
  [1650510486000,0],[1650510498000,0],[1650510504000,0],[1650510506000,0],
  [1650510510000,0],[1650510516000,0],[1650510527000,16],[1650510534000,16],
  [1650510540000,16],[1650510542000,16],[1650510546000,16],[1650510551000,12],
  [1650510557000,11],[1650510563000,11],[1650510569000,12],[1650510575000,18],
  [1650510581000,30],[1650510592000,30],[1650510594000,30],[1650510598000,32],
  [1650510609000,32],[1650510621000,32],[1650510624000,32],[1650510626000,32],
  [1650510631000,35],[1650510637000,36],[1650510647000,36],[1650510656000,36],
  [1650510666000,28],[1650510674000,28],[1650510679000,7],[1650510685000,7],
  [1650510689000,2],[1650510700000,2],[1650510717000,2],[1650510720000,0],
  [1650510725000,0],[1650510752000,0],[1650510759000,0],[1650510760000,0],
  [1650510763000,0],[1650510779000,0],[1650510780000,0],[1650510784000,0],
  [1650510798000,13],[1650510805000,13],[1650510810000,6],[1650510816000,7],
  [1650510822000,7],[1650510825000,7],[1650510829000,0],[1650510861000,0],
  [1650510862000,0],[1650510870000,0],[1650510921000,0],[1650510951000,0],
  [1650510983000,0],[1650510985000,0],[1650511016000,0],[1650511047000,0],
  [1650511078000,0],[1650511108000,0],[1650511117000,0],[1650511138000,0],
  [1650511147000,0],[1650511152000,0],[1650511158000,0],[1650511171000,0],
  [1650511176000,0],[1650511177000,0],[1650511179000,0],[1650511184000,0],
  [1650511191000,0],[1650511197000,0],[1650511202000,0],[1650511208000,0],
  [1650511225000,0],[1650511231000,0],[1650511234000,0],[1650511249000,0],
  [1650511255000,0],[1650511260000,0],[1650511266000,0],[1650511276000,45],
  [1650511284000,41],[1650511293000,39],[1650511303000,31],[1650511314000,35],
  [1650511324000,41],[1650511333000,39],[1650511343000,26],[1650511350000,20],
  [1650511356000,14],[1650511362000,16],[1650511368000,16],[1650511373000,18],
  [1650511379000,18],[1650511384000,16],[1650511390000,23],[1650511398000,3],
  [1650511412000,1],[1650511420000,0],[1650511425000,0],[1650511441000,0],
  [1650511450000,0],[1650511473000,0],[1650511479000,0],[1650511488000,0],
  [1650511518000,0],[1650511548000,0],[1650511552000,0],[1650511589000,0],
  [1650511621000,0],[1650511655000,0],[1650511686000,0],[1650511717000,0],
  [1650511747000,0],[1650511779000,0],[1650511809000,0],[1650511841000,0],
  [1650511852000,0],[1650511882000,0],[1650511912000,0],[1650511934000,0],
  [1650511939000,0],[1650511940000,0],[1650511943000,0],[1650511973000,0],
  [1650511974000,0],[1650511979000,0],[1650511984000,19],[1650512001000,20],
  [1650512007000,20],[1650512010000,20],[1650512012000,13],[1650512018000,7],
  [1650512024000,7],[1650512029000,4],[1650512035000,2],[1650512066000,2],
  [1650512069000,6],[1650512076000,6],[1650512081000,35],[1650512088000,30],
  [1650512095000,30],[1650512100000,27],[1650512106000,33],[1650512115000,33],
  [1650512120000,0],[1650512147000,0],[1650512152000,0],[1650512153000,14],
  [1650512159000,14],[1650512164000,32],[1650512170000,32],[1650512175000,52],
  [1650512182000,54],[1650512189000,54],[1650512191000,13],[1650512197000,15],
  [1650512203000,15],[1650512208000,13],[1650512214000,13],[1650512220000,14],
  [1650512227000,15],[1650512233000,12],[1650512239000,12],[1650512244000,0],
  [1650512250000,0],[1650512281000,0],[1650512285000,0],[1650512287000,0],
  [1650512289000,0],[1650512318000,0],[1650512348000,0],[1650512378000,0],
  [1650512409000,0],[1650512439000,0],[1650512441000,0],[1650512454000,0],
  [1650512455000,0],[1650512464000,0],[1650512469000,0],[1650512475000,1],
  [1650512485000,1],[1650512487000,40],[1650512497000,64],[1650512503000,58],
  [1650512510000,47],[1650512518000,47],[1650512520000,47],[1650512522000,26],
  [1650512528000,38],[1650512537000,41],[1650512545000,34],[1650512553000,34],
  [1650512559000,5],[1650512575000,0],[1650512594000,0],[1650512598000,0],
  [1650512624000,0],[1650512625000,0],[1650512626000,0],[1650512630000,0],
  [1650512635000,15],[1650512641000,15],[1650512646000,15],[1650512651000,16],
  [1650512657000,17],[1650512663000,17],[1650512668000,17],[1650512674000,17],
  [1650512679000,18],[1650512698000,18],[1650512699000,1],[1650512716000,0],
  [1650512721000,0],[1650512746000,0],[1650512755000,0],[1650512758000,0],
  [1650512767000,0],[1650512769000,0],[1650512797000,0],[1650512798000,0],
  [1650512827000,0],[1650512857000,0],[1650512887000,0],[1650512917000,0],
  [1650512947000,0],[1650512977000,0],[1650513008000,0],[1650513041000,0],
  [1650513098000,0],[1650513099000,0],[1650513131000,0],[1650513162000,0],
  [1650513192000,0],[1650513224000,0],[1650513254000,0],[1650513285000,0],
  [1650513317000,0],[1650513348000,0],[1650513397000,0],[1650513398000,0],
  [1650513427000,0],[1650513457000,0],[1650513488000,0],[1650513518000,0],
  [1650513549000,0],[1650513579000,0],[1650513610000,0],[1650513640000,0],
  [1650513698000,0],[1650513728000,0],[1650513758000,0],[1650513788000,0],
  [1650513818000,0],[1650513848000,0],[1650513878000,0],[1650513908000,0],
  [1650513938000,0],[1650513997000,0],[1650513998000,0],[1650514027000,0],
  [1650514057000,0],[1650514088000,0],[1650514119000,0],[1650514149000,0],
  [1650514179000,0],[1650514210000,0],[1650514240000,0],[1650514297000,0],
  [1650514298000,0]
];

option = {
  xAxis: {
    type: 'time',
  },
  yAxis: {},
  dataZoom: [
    {
      type: 'inside',
    },
    {
      type: 'slider',
    }
  ],
  series: [
    {
      type: 'line',
      symbol: 'none',
      data: data,
    },
  ]
};
    
myChart.setOption(option);
```
 
3. Run

### Current Behavior

Data shadow line in bottom dataZoom does not match with serie line on graph
Untitled

### Expected Behavior

data shadow line in dataZoom must match with serie data on graph

### Environment

```markdown
- OS: Any
- Browser: Chrome
- Framework: Any
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by andrearoota**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?
Fix render data shadow line with data not equally distributed in time axis

### Fixed issues
#16924
#15921
#16980

### Before: What was the problem?
Data shadow line in bottom dataZoom does not match with serie line on graph

image

### After: How is it fixed in this PR?
If type of axis is set to "time", scale the original axis data range to dataZoom axis range
I used this [mathematical formula](https://stats.stackexchange.com/questions/281162/scale-a-number-between-a-range)

image

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [x] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/component/dataZoom/SliderZoomView.ts [hunk 1]
```diff
@@ -387,26 +388,35 @@ class SliderZoomView extends DataZoomView {
...
+            let thisCoord = -step;
 
             // Optimize for large data shadow
             const stride = Math.round(data.count() / size[0]);
             let lastIsEmpty: boolean;
-            data.each([otherDim], function (value: ParsedValue, index) {
-                if (stride > 0 && (index % stride)) {
+
+            data.each([info.thisDim, otherDim], function (thisValue: ParsedValue, otherValue: ParsedValue, index) {
+                if (stride > 0 && (index % stride) && info.thisAxis.type !== 'time') {
```
Comment (pissang) [inline src/component/dataZoom/SliderZoomView.ts:399]: Avoid doing `info.thisAxis.type !== 'time'` check in the data loop. It may affect the performance when having large amount of data. Instead we can cache the check result outside the loop

**Comment by Ovilia** [comment]
I'm also fixing related problems at #17311 . I will check the logic more carefully later. Thanks for your contribution!

**Comment by piotrbubelE** [comment]
Hello! Is there a plan to merge this PR anytime soon?
It also enables workaround for bug with axis.min and axis.max on dataShadow

**Comment by pchrzaszczewski** [comment]
I am also waiting for this fix. What are your plans?

**Comment by kamilapolewczykatos** [comment]
Merge would be great. I need this fix for my app.

**Comment by zsamotsil** [comment]
It would be great to Merge ship it. Need also this fix in my application.

**Comment by piotrbubelE** [comment]
Here is issue that can use workaround from this PR:
https://github.com/apache/echarts/issues/19957

**Comment by Bernard-code** [comment]
I really could use this fix. When will this be available to use?

**Comment by grzesikj** [comment]
Add it, please.

**Comment by grzesikj** [comment]
When can you add it?

**Comment by noahhai** [comment]
Fix PR pending for two years 😭

**Comment by pchrzaszczewski** [comment]
Should we spam somehow this topic in anticipation of the answer?
Echarts team give us some answer. 

I give you some possible options. I hope it will help you to respond to the community:

- "we are already working on it, fix will be available in... _insert date here_",
- "it was solved differently, here you have the solution...", 
- "we don't care", 
- "we don't give a shit", 
- "go to hell"

Choose wisely. We will know what to do next... :disappointed:

**Comment by noahhai** [comment]
@pchrzaszczewski Woah easy there. I get the frustration though.

I am going to create a pnpm patch based on the fixes in the PR and just pin the echarts version in my dependencies. Not great, but I assume at *some* point it will get fixed.

**Comment by andrearoota** [comment]
> @pchrzaszczewski Woah easy there. I get the frustration though.
> 
> I am going to create a pnpm patch based on the fixes in the PR and just pin the echarts version in my dependencies. Not great, but I assume at _some_ point it will get fixed.

Does my code still work in the current version? I am willing to improve it and update it if necessary

**Comment by pchrzaszczewski** [comment]
> @pchrzaszczewski Woah easy there. I get the frustration though.
> 
> I am going to create a pnpm patch based on the fixes in the PR and just pin the echarts version in my dependencies. Not great, but I assume at _some_ point it will get fixed.

@noahhai I'm grateful that you responded. We can see that something is happening ;)

I've been patient for 2 years :muscle: It is always better to at least know if there is a plan or not.
I'm keeping my fingers crossed and cheering that the day will finally come... :crossed_fingers:

**Comment by grzesikj** [comment]
I'm still waiting

**Comment by alinscodes** [comment]
Can we just deploy this pleasE?

**Review by alinscodes — APPROVED** [review]
This is good.

**Comment by ElicaInc** [comment]
@andrearoota fixed the mismatch between the chart and dataZoom. It works well in my setup—thank you, @andrearoota! I hope this fix will be included in the official echarts release.

**Comment by alinscodes** [comment]
Lets get this in please

**Comment by ElicaInc** [comment]
This patch, made possible thanks to @andrearoota, worked perfectly in my setup while waiting for the official merge.
```
diff --git a/node_modules/echarts/lib/component/dataZoom/SliderZoomView.js b/node_modules/echarts/lib/component/dataZoom/SliderZoomView.js
index be21afa..25e561e 100644
--- a/node_modules/echarts/lib/component/dataZoom/SliderZoomView.js
+++ b/node_modules/echarts/lib/component/dataZoom/SliderZoomView.js
@@ -281,22 +281,35 @@ var SliderZoomView = /** @class */function (_super) {
       var areaPoints_1 = [[size[0], 0], [0, 0]];
       var linePoints_1 = [];
       var step_1 = thisShadowExtent[1] / (data.count() - 1);
-      var thisCoord_1 = 0;
+        // Added: Variables to support time axis
+      var thisDataExtent = data.getDataExtent(info.thisDim);
+      var normalizationConstant = size[0] / (thisDataExtent[1] - thisDataExtent[0]);
+      var isTimeAxis = info.thisAxis.type === 'time';
+      var thisCoord_1 = -step_1;
       // Optimize for large data shadow
       var stride_1 = Math.round(data.count() / size[0]);
       var lastIsEmpty_1;
-      data.each([otherDim], function (value, index) {
-        if (stride_1 > 0 && index % stride_1) {
-          thisCoord_1 += step_1;
+      data.each([info.thisDim, otherDim], function (thisValue, otherValue, index) {
+        if (stride_1 > 0 && (index % stride_1)) {
+          // Added: Only increment step when not using a time axis
+          if (!isTimeAxis) {
+            thisCoord_1 += step_1;
+          }
           return;
         }
+        
+        // Fix: Coordinate calculation split between time axis and non-time axis
+        thisCoord_1 = isTimeAxis
+          ? (+thisValue - thisDataExtent[0]) * normalizationConstant
+          : thisCoord_1 + step_1;
+    
         // FIXME
         // Should consider axis.min/axis.max when drawing dataShadow.
         // FIXME
         // 应该使用统一的空判断？还是在list里进行空判断？
-        var isEmpty = value == null || isNaN(value) || value === '';
+        var isEmpty = otherValue == null || isNaN(otherValue) || otherValue === '';
         // See #4235.
-        var otherCoord = isEmpty ? 0 : linearMap(value, otherDataExtent_1, otherShadowExtent_1, true);
+        var otherCoord = isEmpty ? 0 : linearMap(otherValue, otherDataExtent_1, otherShadowExtent_1, true);
         // Attempt to draw data shadow precisely when there are empty value.
         if (isEmpty && !lastIsEmpty_1 && index) {
           areaPoints_1.push([areaPoints_1[areaPoints_1.length - 1][0], 0]);
@@ -307,7 +320,7 @@ var SliderZoomView = /** @class */function (_super) {
         }
         areaPoints_1.push([thisCoord_1, otherCoord]);
         linePoints_1.push([thisCoord_1, otherCoord]);
-        thisCoord_1 += step_1;
+        
         lastIsEmpty_1 = isEmpty;
       });
       polygonPts = this._shadowPolygonPts = areaPoints_1;

```

**Comment by carlos-manuel-soares-alb** [comment]
Any news for this PR to be merged?

**Review by sameer-ahmd — APPROVED** [review]

**Review by 100pah — APPROVED** [review]

**Comment by Bilge** [comment]
Does this address #13408 or nah?

Spoiler: it only half fixes it. It fixes the time series issue but not the step line issue.
