### PR TITLE
fix(radar): fix radar symbol border is scaled

### LINKED ISSUE #14836: 雷达图的描边单位
### Version
5.0.2

### Steps to reproduce
echarts5的series-radar-symbolSize改变，series-radar-itemStyle-borderWidth也变化。是不是单位echarts4和echarts5的单位发生了变化？或者borderWidth的默认半径设置错误？

### What is expected?
和echarts4一样，borderWidth显示正常

### What is actually happening?
echarts4
9I`7TNNQXYZX4D5P_N%E~GS

echarts5
IKZP14{UCBGFEC E2ZNP6@S

### PR DESCRIPTION
**Pull request by pissang**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Fix border is scaled in radar chart.

### Fixed issues

Close #14836

### CODE REVIEW

**Review by 100pah — APPROVED** [review]

File: src/chart/radar/RadarView.ts [hunk 1]
```diff
@@ -238,6 +238,7 @@ class RadarView extends ChartView {
                 else {
                     symbolPath.useStyle(itemStyle);
                     symbolPath.setColor(color);
+                    symbolPath.style.strokeNoScale = true;
```
Comment (zxflslzyx) [inline src/chart/radar/RadarView.ts:241]: Excuse me，do you know when this amendment will be published?

**Comment by zxflslzyx** [comment]
Could you tell me  When  it  will  be  published , please?
