### PR TITLE
fix(tree): error when running setOption twice with diff data

### LINKED ISSUE #14858: Tree chart error when running setOption twice with different data
### Version
5.1.0

### Reproduction link
[https://jsfiddle.net/YeongCY/qythgp31/](https://jsfiddle.net/YeongCY/qythgp31/)

### Steps to reproduce
1. Build a tree chart with a set of data
2. Assign the tree chart with another set of data (using setOption with notMerge param is set to true)
3. The browser console shows the error message: "Uncaught TypeError: Cannot read property 'children' of undefined".

### What is expected?
The tree chart should be able to show the second set of data without any error message.

### What is actually happening?
The browser console shows the error message: "Uncaught TypeError: Cannot read property 'children' of undefined".

### PR DESCRIPTION
**Pull request by Map1en**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Fixed the bug of running setOption twice in tree chart with different data

### Fixed issues

close #14858

### Before: What was the problem?
Tree chart error when running setOption twice with different data

### After: How is it fixed in this PR?

Using optional chains

And add one visual test

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

test/tree-setoption-twice.html

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/chart/tree/TreeSeries.ts [hunk 1]
```diff
@@ -149,7 +149,7 @@ class TreeSeriesModel extends SeriesModel<TreeSeriesOption> {
         function beforeLink(nodeData: List) {
             nodeData.wrapMethod('getItemModel', function (model, idx) {
                 const node = tree.getNodeByDataIndex(idx);
-                if (!node.children.length || !node.isExpand) {
+                if (!node?.children.length || !node.isExpand) {
```
Comment (pissang) [inline src/chart/tree/TreeSeries.ts:152]: We avoid using optional chaining in our code because it is easy to generate lots of unnecessary code after compiled.
```ts
if (!(node && node.children.length && node.isExpand))
``` 
 will be much simpler here.

**Review by pissang — CHANGES_REQUESTED** [review]

**Review by pissang — APPROVED** [review]
