### PR TITLE
fix: hightlight multiple series not work as expected

### LINKED ISSUE #15204: 折线图设置series.emphasis， 然后在chart示例上dispatchAction（{type: 'downplay'}），只能高亮一条折线
### Version
5.1.1

### Steps to reproduce
我在echartsde demo上改了一下，下面是配置

```js
option = {
    legend: {
        data: ['Direct', 'Mail Ad', 'Affiliate Ad', 'Video Ad', 'Search Engine']
    },
    xAxis: {
        type: 'value'
    },
    yAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    series: [
        {
            name: 'Direct',
            type: 'line',
            label: {
                show: true
            },
            emphasis: {
                focus: 'series'
            },
            data: [320, 302, 301, 334, 390, 330, 320]
        },
        {
            name: 'Mail Ad',
            type: 'line',
            label: {
                show: true
            },
            emphasis: {
                focus: 'series'
            },
            data: [120, 132, 101, 134, 90, 230, 210]
        },
        {
            name: 'Affiliate Ad',
            type: 'line',
            label: {
                show: true
            },
            emphasis: {
                focus: 'series'
            },
            data: [220, 182, 191, 234, 290, 330, 310]
        },
        {
            name: 'Video Ad',
            type: 'line',
            label: {
                show: true
            },
            emphasis: {
                focus: 'series'
            },
            data: [150, 212, 201, 154, 190, 330, 410]
        }
    ]
};
myChart.getZr().on('mouseover', (params) => {
    const { target, topTarget } = params;
    myChart.dispatchAction({
        type: 'highlight',
        seriesIndex: [0, 1, 2],
  })
})
```

### What is expected?
当鼠标放到第一条线上，期望能第一 第二 第三条线高亮

### What is actually happening?
鼠标放到第一条线上，只高亮了第三条

### PR DESCRIPTION
**Pull request by ssthouse**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### Fixed issues

Close #15204

### Before: What was the problem?

Dispatch `hightlight` action with the following code only highlight the lastest series; The expected result is all three series are highlighted;

```javascript
dispatchAction({
    type: 'highlight',
    seriesIndex: [0, 1, 2],
});
```

image

### After: How is it fixed in this PR?

Fix the logic of running **blur unHighlighted series** multiple times;

Jun-22-2021 13-10-57

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by pissang** [comment]
The fix looks neat! 

The test case is better to be put in `hoverFocus2.html`

**Comment by ssthouse** [comment]
> The fix looks neat! One suggestion: this test case can be put in `hoverFocus2.html`. It has similar cases

fixed~

File: src/core/echarts.ts [hunk 1]
```diff
@@ -1489,11 +1489,13 @@ class ECharts extends Eventful<ECEventDefinition> {
...
 
             // If dispatchAction before setOption, do nothing.
-            ecModel && ecModel.eachComponent(condition, function (model) {
+            ecModel && ecModel.eachComponent(condition, function (model, modelIndex) {
                 if (!excludeSeriesIdMap || excludeSeriesIdMap.get(model.id) == null) {
                     if (isHighDownPayload(payload)) {
                         if (model instanceof SeriesModel) {
-                            if (payload.type === HIGHLIGHT_ACTION_TYPE && !payload.notBlur) {
+                            // only blur once
+                            const isFirstTimeBlur = modelIndex === 0;
```
Comment (pissang) [inline src/core/echarts.ts:1497]: In some cases `modelndex` may not be `0`. It the index in the option. For example: if we change the test code to:
```ts
chart.dispatchAction({
  type: 'highlight',
  seriesIndex: [1],
 });
```

The `modelIndex` of the first iteration will be `1`. And no series will be blurred, which is not expected.

I think a better solution is using a flag to check if any series triggers blur.


There is another situation I think we need to consider:
If we set `blurScope` to `series`. Only other data in the same series will be blurred. Should we still use the "only one series will trigger blur" policy?

**Review by pissang — CHANGES_REQUESTED** [review]

File: src/core/echarts.ts (hunk 1 above)
Comment (pissang) [reply src/core/echarts.ts:1497]: Another unrelated suggestion: 

I think the old case you are using can be added to `hoverFocus.html`. It's more clear.

Comment (ssthouse) [reply src/core/echarts.ts]: @pissang Hi~
> In some cases modelndex may not be 0. It’s the index in the option. 

I have changed to flag implementation now~
(I was thinking that the second params `index` always starts with zero like `Array.forEach`.  )

> There is another situation I think we need to consider:
If we set blurScope to series. Only other data in the same series will be blurred. Should we still use the "only one series will trigger blur" policy?

I think when `blurScope === 'series'`, we can stick to the original _blur all_ logic.

> I think the old case you are using can be added to hoverFocus.html. It's more clear.

👌   I have moved the old testcase into the `hoverFocus.html`.

**When blurScope="series"**
Jun-23-2021 17-26-08


**When blurScope!="series"**
Jun-23-2021 17-24-51

Comment (pissang) [reply src/core/echarts.ts]: > (I was thinking that the second params index always starts with zero like Array.forEach. )

Yeah, this API design may be misleading.

> I think when blurScope === 'series', we can stick to the original blur all logic.

There is another option `blurScope: 'coordinateSystem'` may have a similar issue. I'm thinking if we can support multiple series in https://github.com/apache/echarts/blob/4e671b6c95c1fe9606d2cdbdd4980a54ea47665c/src/util/states.ts#L514 and https://github.com/apache/echarts/blob/4e671b6c95c1fe9606d2cdbdd4980a54ea47665c/src/util/states.ts#L408 . Perhaps it's a better place to do this complex logic.

BTW: in the code of `blurSeries`, this comment can be removed to avoid confusion.
```ts
 // TODO blurScope: coordinate system
```

Comment (ssthouse) [reply src/core/echarts.ts]: @pissang I moved the logic into `echarts/src/util/states.ts`; 
(ps: the code modification in `src/core/echarts.ts` now is to improve code readability)

And for `blurScope: 'coordinateSystem'`, a new testcase is added in `hoverFocus.html`

coordinate

File: src/util/states.ts [hunk 2]
```diff
@@ -437,7 +438,10 @@ export function blurSeries(
 
     const blurredSeries: SeriesModel[] = [];
 
-    ecModel.eachSeries(function (seriesModel) {
+    ecModel.eachSeries(function (seriesModel, seriesIndex) {
+        if (excludedSeriesIndexes && excludedSeriesIndexes.includes(seriesIndex)) {
```
Comment (pissang) [inline src/util/states.ts:442]: `includes` is not supported in IE 9+, which we still supported currently. We can use `zrUtil.indexOf(excludedSeriesIndexes, seriesIndex) >= 0` instead.

File: src/util/states.ts [hunk 3]
```diff
@@ -529,11 +532,12 @@ export function blurSeriesFromHighlightPayload(
             el = data.getItemGraphicEl(current++);
         }
     }
+    const excludedSeriesIndexes = payload.seriesIndex || [];
```
Comment (pissang) [inline src/util/states.ts:535]: `seriesIndex` is one of the possible queries. Developers can also use `payload.seriesId` to query target series. Perhaps we need to query the highlight `seriesModel` list in `echarts.ts` and pass it to this function.

Also, I'm not sure if there is a logic issue:

If we have `focus: 'self'` in one series and dispatch a `highlight` action on this series. This series will also be in this `excludedSeriesIndexes` and not perform the `focus: 'self'` strategy.

File: src/util/states.ts [hunk 4]
```diff
@@ -409,7 +409,8 @@ export function blurSeries(
     targetSeriesIndex: number,
     focus: InnerFocus,
     blurScope: BlurScope,
-    api: ExtensionAPI
+    api: ExtensionAPI,
+    excludedSeriesIndexes?: number[]
```
Comment (pissang) [inline src/util/states.ts:413]: Should be indices instead of indexes.

File: test/data/basicChartsOptions.js [hunk 5]
```diff
@@ -1,5 +1,223 @@
...
+                name: "Video Ad",
+                type: "line",
+                label: {
+                    show: true,
+                },
+                data: [150, 212, 201, 154, 190, 330, 410],
+                emphasis: coordinateSystemBlurEmphasis,
+            },
+        ],
+    },
```
Comment (pissang) [inline test/data/basicChartsOptions.js:220]: Seems these new cases are mainly target for the hover focus feature. We can append them in `hoverFocus.html` instead of adding them in the `basicChartOptions`. Options in `basicChartOptions` are usually very basic and will be used in tests of many features.

Also, if we want to add a new test case, always adding it at the tail instead of the head. Or it will affect the replay of user interactions in the automatic visual regression testing tool.

**Review by pissang — CHANGES_REQUESTED** [review]

File: src/util/states.ts (hunk 2 above)
Comment (ssthouse) [reply src/util/states.ts]: fixed

File: src/util/states.ts (hunk 3 above)
Comment (ssthouse) [reply src/util/states.ts]: > Also, I'm not sure if there is a logic issue:
>
> If we have focus: 'self' in one series and dispatch a highlight action on this series. This series will also be in this excludedSeriesIndexes and not perform the focus: 'self' strategy.

Yes, There is a logic issue. I add another testcase for this.
Please take a look if this is the expected result~

Jun-26-2021 20-31-19

File: src/util/states.ts (hunk 4 above)
Comment (ssthouse) [reply src/util/states.ts]: fixed

File: test/data/basicChartsOptions.js (hunk 5 above)
Comment (ssthouse) [reply test/data/basicChartsOptions.js]: got it, fixed~

File: src/util/states.ts [hunk 6]
```diff
@@ -454,7 +457,8 @@ export function blurSeries(
             || blurScope === 'coordinateSystem' && !sameCoordSys
             // Not blur self series if focus is series.
             || focus === 'series' && sameSeries
-            // TODO blurScope: coordinate system
+            // Not blur other series if focus is self
+            || focus === 'self' && !sameSeries
```
Comment (pissang) [inline src/util/states.ts:461]: We still need to blur other series if `blurScope` is 'global' and `focus` is 'self'. You can run visual regression test(VRT in short) on `hoverFocus.html`, `hoverFocus2.html` to see if anythings breaks. The command of starting VRT is:
```ts
npm run test:visual
```

**Review by pissang — CHANGES_REQUESTED** [review]

File: src/util/states.ts (hunk 6 above)
Comment (ssthouse) [reply src/util/states.ts]: @pissang Hi，I found it's complicated to first blur then highlight for each series, like this;
```javascript
for(const series of seriesList){
    blurNecessaryPart(series);
    highlightCurrent(series);
}
```

Since the previous highlighted series can be easily blurred by the latter series;
It may be more clear if we first blur all the necessary parts then hight all the necessary parts, like this;

```javascript
for(const series of seriesList){
    blurNecessaryPart(series);
}
for(const series of seriesList){
    highlightCurrent(series);
}
```

I modified the current code to this scenario and tested with `npm run test:visual`, please take a look~

Comment (pissang) [reply src/util/states.ts]: @ssthouse That's brilliant! It should work well. I can't find other issues. The only thing that needs to be done is record the user interactions on the new add test case so we can test it automatically.

You can click the `Record Interaction` on the VRT page button to open the recording page. Then follow the hint on the page and use the shortcut key to start recording. During the recording, you can click buttons, hover elements. Each click will trigger a screenshot to compare, but hover won't. So if you want to compare the current picture, you should at least click or use the shortcut key to trigger the screenshot. 

Usually, each action needs to focus on one test case and the interaction count in each action should be as less as possible. Feel free to ask me if you have problems on it.

Comment (ssthouse) [reply src/util/states.ts]: @pissang I have recorded the testcases and tried to run them. 
Currently, it failed(as expected), is there anything I should do to make it pass?

image

**Review by pissang — APPROVED** [review]
