### PR TITLE
fix(treemap): label.show=false will throw error

### LINKED ISSUE #15140: treemap throws when series label set { show: false } property.
### Version
5.1.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=treemap-obama](https://echarts.apache.org/examples/zh/editor.html?c=treemap-obama)

### Steps to reproduce
1. open the example: https://echarts.apache.org/examples/zh/editor.html?c=treemap-obama
2. in the function `createSeriesCommon`, line 132, set label.normal.show = false

then you will see the errors.

### What is expected?
This is what stopped me from trying to upgrade from V4 right now in my project, i hope a bugfix with it in time.

### What is actually happening?
this result in my page crashed so I think it is important to fix it.

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

If treemap label is set to not show, then just return it

### Fixed issues

Close #15140 15140

### Before: What was the problem?
Screen Shot 2021-06-12 at 9 59 31 PM

### After: How is it fixed in this PR?

Screen Shot 2021-06-12 at 9 59 09 PM

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [x] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/chart/treemap/TreemapView.ts [hunk 1]
```diff
@@ -979,6 +979,9 @@ function renderNode(
             }
         );
 
+        if (!isShow) {
```
Comment (pissang) [inline src/chart/treemap/TreemapView.ts:982]: textEl is also needed when label is set `emphasis.show = true`. Perhaps we can check if `textEl` is null in the next line instead of check if show on normal state.

**Review by pissang — CHANGES_REQUESTED** [review]

File: src/chart/treemap/TreemapView.ts (hunk 1 above)
Comment (susiwen8) [reply src/chart/treemap/TreemapView.ts:982]: Right, I missed that.

Comment (susiwen8) [reply src/chart/treemap/TreemapView.ts]: @pissang The reason is in `labelStyle`, a text element needs to be create should consider all four state, but in `treemap`, it only consider `normal` state.

Comment (pissang) [reply src/chart/treemap/TreemapView.ts]: @susiwen8 Year we need to check all four states. But it has been done in `setLabelStyle`. text element will be created if any state is set `show: true`. So I think we only need to check if `rectEl.getTextContent()` exists.

Comment (susiwen8) [reply src/chart/treemap/TreemapView.ts]: @pissang Thx, You are right.

**Review by pissang — APPROVED** [review]
