### PR TITLE
fix(marker): fix `markArea` doesn't show when using `x/y` pixel but `coord` is not defined

### LINKED ISSUE #17344: [Bug] that cannot be rendered normally when makearea data is the scale field between two screen coordinates
### Version

5.3.3

### Link to Minimal Reproduction

https://codepen.io/zxyt/pen/QWmEjVo?editors=0010

### Steps to Reproduce

设置markArea的data为
[
           {
              name: '两个屏幕坐标之间的标域',
              x: 100,
              y: 100
            },
            {
              x: '90%',
              y: '10%'
            }
]

### Current Behavior

无法渲染出markArea

### Expected Behavior

正确渲染markArea

### Environment

```markdown
- OS: windows 11
- Browser: edge 103.0.1264.49 (正式版本) (64 位)
- Framework: vanillajs
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by jiawulin001**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Fix the error that occurs when declaring area with x/y in `markArea`

### Fixed issues

- #5832
- #7055
- #10074
- fix #17344

### Before: What was the problem?

As is described in issues, when setting x and y to denote an area for `markArea`, the error occurs. This is caused becasue `lt` and `rb` returned by `dataTransform()` has no attribute `coord` when user does not specify `coord` in `markArea.data`. So when running the following code, Echarts reads `lt.coord` and throw an error.
https://github.com/apache/echarts/blob/11a9247e7fab2e6ff9c60b545ba775e8c1b2412f/src/component/marker/MarkAreaView.ts#L69-L79
image

### After: How does it behave after the fixing?

Now before `dataTransform()` return an `item`, a check is added and make sure there's a `coord` attribute in it (even `coord` is not needed). And there will be no errors caused by this.

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [x] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/component/marker/markerHelper.ts [hunk 1]
```diff
@@ -147,6 +147,9 @@ export function dataTransform(
             item.coord = coord;
         }
     }
+    if (item.coord == null) {
+        item.coord = [];
```
Comment (Ovilia) [inline src/component/marker/markerHelper.ts:151]: I'm not sure but returning an array with 0 element doesn't seem to be *valid* by logic for the `coord`. What do you think if it returns `[null, null]`? Can you help test if it works?

**Review by Ovilia — CHANGES_REQUESTED** [review]

File: src/component/marker/markerHelper.ts (hunk 1 above)
Comment (plainheart) [reply src/component/marker/markerHelper.ts:148]: I think it's fine to return an empty array. But I found another potential bug when `coord` includes the special type string like [`min/max/median/average`](https://echarts.apache.org/zh/option.html#series-bar.markArea.data:~:text=%7D%0A%20%20%20%20%5D%2C%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%27-,%E6%89%80%E6%9C%89%E6%95%B0%E6%8D%AE%E8%8C%83%E5%9B%B4%E5%8C%BA%E9%97%B4,-%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20coord%3A%20%5B). Just fixed it and added a test case.
