### PR TITLE
Fix: endLabel color support 'auto' 'inherit'

### LINKED ISSUE #13685: endLabel do not support color: 'auto' 'inherit'
### What problem does this feature solve?

Without `color: 'auto'` or `color: 'inherit'`, 
developers can not use the default color on endLabel.

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### Fixed issues

Close #13685

### Before: What was the problem?
Screen Shot 2021-01-10 at 16 25 47

### After: How is it fixed in this PR?

Screen Shot 2021-01-10 at 16 25 33

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

test/line-endLabel.html

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/chart/line/LineView.ts [hunk 1]
```diff
@@ -609,6 +610,8 @@ class LineView extends ChartView {
             }
         }
         this._clipShapeForSymbol = clipShapeForSymbol;
+        const visualColor = getVisualGradient(data, coordSys)
```
Comment (pissang) [inline src/chart/line/LineView.ts:613]: I think it's not appropriate to use a gradient on the endLabel. Perhaps it's better to pick the last color from the gradient stops?

**Review by pissang — CHANGES_REQUESTED** [review]

File: src/chart/line/LineView.ts (hunk 1 above)
Comment (susiwen8) [reply src/chart/line/LineView.ts:613]: Yes, It should use `convertToColorString ` to convert it @pissang

Comment (pissang) [reply src/chart/line/LineView.ts:613]: Nice fix! I didn't notice the exists of `convertToColorString`

**Review by pissang — APPROVED** [review]
