### PR TITLE
fix(treemap): error when running setOption twice with diff data

### LINKED ISSUE #14857: Treemap chart error when setOption twice with dfifferent data
### Version
5.1.0

### Reproduction link
[https://jsfiddle.net/YeongCY/Ldp1xnsj/](https://jsfiddle.net/YeongCY/Ldp1xnsj/)

### Steps to reproduce
1. Build a treemap chart and a set of data.
2. Assign the treemap chart with another set of data (using setOption with notMerge param is set to true).
3. The browser console show the an error message: Uncaught TypeError: Cannot read property 'depth' of undefined" and the treemap's tile color will change when hover on it.

### What is expected?
The treemap should show the second set of data without any error message. 

### What is actually happening?
The browser console show the an error message: Uncaught TypeError: Cannot read property 'depth' of undefined" and the treemap's tile color will change when hover on it.

### PR DESCRIPTION
**Pull request by Map1en**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?
Fixed the bug of running setOption twice in treemap chart with different data

### Fixed issues
close #14857

### Before: What was the problem?
treemap error when running setOption twice with diff data

### After: How is it fixed in this PR?
use ternary operator
add one visual test
rename one visual test

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

test/treemap-setOption-twice.html

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/chart/treemap/TreemapSeries.ts [hunk 1]
```diff
@@ -370,7 +370,7 @@ class TreemapSeriesModel extends SeriesModel<TreemapSeriesOption> {
         function beforeLink(nodeData: List) {
             nodeData.wrapMethod('getItemModel', function (model, idx) {
                 const node = tree.getNodeByDataIndex(idx);
-                const levelModel = levelModels[node.depth];
+                const levelModel = levelModels[node ? node.depth : undefined];
```
Comment (pissang) [inline src/chart/treemap/TreemapSeries.ts:373]: It's more clear to write as:
```
const levelModel = node ? levelModels[node.depth] : null;
```

**Review by pissang — CHANGES_REQUESTED** [review]

**Review by pissang — APPROVED** [review]
