### PR TITLE
Fix(handleIcon): icon without 'path://' will block

### LINKED ISSUE #14014: dataZoom-slider.handleIcon  在使用base64的dataURI的时候页面会崩溃
### Version
5.0.0

### Steps to reproduce
see as
5.0: https://codepen.io/facingcheer/pen/OJRBLJN
4.8: https://codepen.io/facingcheer/pen/MWjPgoX
当前的demo中 使用4.8.0版本的handleIcon可以正常渲染
5.0中如果激活handleIcon页面会崩溃

### What is expected?
5.0中handleIcon依然支持dataURI语法

### What is actually happening?
暂不支持

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

`path://` prefix is in wrong position

### Fixed issues

Close #14014

### Before: What was the problem?

`handleIcon` was base64 might block render

### After: How is it fixed in this PR?

Chart render successfully.

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [x] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/util/symbol.ts [hunk 1]
```diff
@@ -364,6 +364,10 @@ export function createSymbol(
         ) as unknown as ECSymbol;
     }
     else {
+        // Compatitable with the old icon parsers. Which can use a path string without path://
+        if (symbolType.indexOf('path://') < 0) {
+            symbolType = 'path://' + symbolType;
```
Comment (pissang) [inline src/util/symbol.ts:369]: It wil break the code that set `symbol` to `rect`, `cirlce`

**Review by pissang — CHANGES_REQUESTED** [review]

**Review by pissang — APPROVED** [review]
