### PR TITLE
Fix(pie): labelLine is not hidden in some case

### LINKED ISSUE #13871: 饼图通过setOption更新label位置时，引导线未自动隐藏
### Version
5.0.0

### Steps to reproduce
1.使用饼图新增labelLayout属性时发现，如果标签位置在外部，引导线默认展示，初始设置hideOverlap为false，通过setOption的方法更新hideOverlap为true后，发现只有label隐藏，对应的引导线未自动隐藏。
2.如果初始label在饼图外部，引导线是默认展示的情况下，通过setOption调整label位置为inside后，引导线未自动隐藏。

### What is expected?
未设置lineStyle，饼图通过setOption更新label位置时，引导线应根据label 的不同位置显示与隐藏

### What is actually happening?
目前引导线仍显示

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Add `showLabelLine` param for `setLabelLineStyle` to control `labelLine` should be drawn or removed.

### Fixed issues

Close #13871

### Before: What was the problem?

After second  `setOption`. `labelLine` didn't hide when `position` is `inside`.

### After: How is it fixed in this PR?

`labelLine` was hidden after second `setOption`

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

The last test case in `pie-label.html`

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/chart/pie/PieView.ts [hunk 1]
```diff
@@ -189,7 +189,7 @@ class PiePiece extends graphic.Sector {
         setLabelLineStyle(this, getLabelLineStatesModels(itemModel), {
```
Comment (pissang) [inline src/chart/pie/PieView.ts:189]: Use a `show` flag in `setLabelLineStyle` is not a good style. It makes this function more complex and obscure because it's not matching with the function name. 

Instead, we should use `labelLine.hide()` when `position` is not 'outside' and `labelLine` has been created explicitly here.

**Review by pissang — CHANGES_REQUESTED** [review]

File: src/chart/pie/PieView.ts [hunk 2]
```diff
@@ -185,6 +185,10 @@ class PiePiece extends graphic.Sector {
             z2: 10
         });
 
+        if (seriesModel.get('label').position !== 'outside') {
```
Comment (pissang) [inline src/chart/pie/PieView.ts:188]: Should always use `seriesModel.get(['label', 'position'])` to avoid null value access.
`outer` should also be considered.

```ts
const position = seriesModel.get(['label', 'position']);
if (position !== 'outside' && position !== 'outer')
```

**Review by pissang — CHANGES_REQUESTED** [review]

**Review by pissang — APPROVED** [review]
