### PR TITLE
fix(graph): user cursor has higher priority

### LINKED ISSUE #12409: 鼠标移入节点的鼠标样式无法更改。
### Version
4.7.0

### Steps to reproduce
在graph图中，设置属性draggable: true, cursor: 'pointer'后，开启拖拽功能后设置的cursor属性无效。

### What is expected?
开启拖拽功能后另支持鼠标样式的设置。

### What is actually happening?
目前不支持上述功能。

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

- Close #12409

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/chart/helper/Symbol.ts [hunk 1]
```diff
@@ -141,10 +141,10 @@ class Symbol extends graphic.Group {
         symbolPath.z = z;
     }
 
-    setDraggable(draggable: boolean) {
+    setDraggable(draggable: boolean, hasCursorOption?: boolean) {
         const symbolPath = this.childAt(0) as ECSymbol;
         symbolPath.draggable = draggable;
-        symbolPath.cursor = draggable ? 'move' : symbolPath.cursor;
+        symbolPath.cursor = hasCursorOption ? symbolPath.cursor : draggable ? 'move' : symbolPath.cursor;
```
Comment (pissang) [inline src/chart/helper/Symbol.ts:147]:
```ts
!hasCursorOption && draggable ? 'move' : symbolPath.cursor
```

Will be neater

**Review by pissang — APPROVED** [review]
