### PR TITLE
fix: markArea display filter correction

### LINKED ISSUE #16853: [Bug] markAreas disappear when zooming in
### Version

5.3.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-sections

### Steps to Reproduce

This code is from the given line chart example, extended by zooming functionality and exact limits for markAreas.

```
option = {
  title: {
    text: 'Distribution of Electricity',
    subtext: 'Fake Data'
  },
  tooltip: {
    trigger: 'axis',
    axisPointer: {
      type: 'cross'
    }
  },
  toolbox: {
    show: true,
    feature: {
      saveAsImage: {}
    }
  },
dataZoom: [{}], // WITH ZOOMING
  xAxis: {
    type: 'category',
    boundaryGap: false,
    // prettier-ignore
    data: ['00:00', '01:15', '02:30', '03:45', '05:00', '06:15', '07:30', '08:45', '10:00', '11:15', '12:30', '13:45', '15:00', '16:15', '17:30', '18:45', '20:00', '21:15', '22:30', '23:45']
  },
  yAxis: {
    type: 'value',
    axisLabel: {
      formatter: '{value} W'
    },
    axisPointer: {
      snap: true
    },
  },
  series: [
    {
      name: 'Electricity',
      type: 'line',
      smooth: true,
      // prettier-ignore
      data: [300, 280, 250, 260, 270, 300, 550, 500, 400, 390, 380, 390, 400, 500, 600, 750, 800, 700, 600, 400],
      markArea: {
        itemStyle: {
          color: 'rgba(255, 173, 177, 0.4)'
        },
        data: [
          [
            {
              name: 'Morning Peak',
              xAxis: '07:30',
              
            },
            {
              xAxis: '10:00',
              yAxis: 700 // EXACT LIMIT HERE
            }
          ],
          [
            {
              name: 'Evening Peak',
              xAxis: '17:30'
            },
            {
              xAxis: '21:15'
            }
          ],
          [
          {yAxis: 200}, {yAxis: 600, xAxis: '22:30'}, // EXACT LIMIT HERE
            ]
        ]
      }
    }
  ]
};
```

### Current Behavior

When applying limits for the markArea, and zooming in, the markAreas disappear. 

So the initial view looks fine:

image

But when you start zooming, markAreas will disappear.

image

Also applied dataZoom filterMode with 'weakFilter', 'empty' and 'none', but these settings did not resolve the issue.

### Expected Behavior

The markAreas should still be visible in the window, also when zooming in.

### Environment

```markdown
- OS: macOS Big Sur
- Browser: Chrome
- Using one of the Echarts examples editor
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by jiawulin001**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Correct the markArea filter when both diagonal points are not in coordinate system.

### Fixed issues

- fix #16853

### Before: What was the problem?

MarkArea will disappear if both anchor points of it are not in the coordinate system.

before#16853

### After: How is it fixed in this PR?

MarkArea is correctly displayed.

after#16853

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

Attached

### CODE REVIEW

File: src/coord/cartesian/Cartesian2D.ts [hunk 1]
```diff
@@ -105,6 +106,18 @@ class Cartesian2D extends Cartesian<Axis2D> implements CoordinateSystem {
             && this.getAxis('y').containData(data[1]);
     }
 
+    containZone(data1: ScaleDataValue[], data2: ScaleDataValue[]): boolean {
+        const zoneCorner1 = this.dataToPoint(data1);
+        const zoneCorner2 = this.dataToPoint(data2);
+        const area = this.getArea();
+        return rectRectIntersect(
```
[the remark this answers is not in the document]
Comment (jiawulin001) [reply src/coord/cartesian/Cartesian2D.ts]: Thank you for pointing that out! BoundingRect.intersect in use now!

File: src/coord/cartesian/Cartesian2D.ts [hunk 2]
```diff
@@ -105,6 +105,17 @@ class Cartesian2D extends Cartesian<Axis2D> implements CoordinateSystem {
             && this.getAxis('y').containData(data[1]);
     }
 
+    containZone(data1: ScaleDataValue[], data2: ScaleDataValue[]): boolean {
+        const zoneDiag1 = this.dataToPoint(data1);
+        const zoneDiag2 = this.dataToPoint(data2);
+        const area = this.getArea();
+        const zoneX = Math.min(zoneDiag1[0], zoneDiag2[0]);
```
Comment (pissang) [inline src/coord/cartesian/Cartesian2D.ts:112]: We can use the `zoneDiag1` and `zoneDiag2` directly when creating `BoundingRect`. It will handle min, max logic in the constructor:

https://github.com/ecomfe/zrender/blob/master/src/core/BoundingRect.ts#L27

File: src/component/marker/MarkAreaView.ts [hunk 3]
```diff
@@ -123,6 +123,20 @@ function markAreaFilter(coordSys: CoordinateSystem, item: MarkAreaMergedItemOpti
         ) {
             return true;
         }
+        /*Another zone filter is applied, which might not be necessary.
+        Directly returning true means displaying markArea component permanently,
```
Comment (pissang) [inline src/component/marker/MarkAreaView.ts:127]: We prefer using inline comment // here.

Also this comment seems to be outdated after new commits?

Comment (jiawulin001) [reply src/component/marker/MarkAreaView.ts:127]: For this one, I mean we are using a function `zonefilter` here, but actually returning true can achieve almost the same effect as using this function. The reason is that, when returning true, `markArea` is always shown and will not be clipped however the grid changes, which solves the problem. When the coordinates does not include the `markArea`, it's automatically not shown. So in my opinion  a function to check if the coordinates intersect with `markArea` is unnecessary. Of course, keeping the `markArea` rendered may be problematic when there are huge amount of them, but in most cases one or two `markArea`s would hardly affect performance.

File: src/coord/cartesian/Cartesian2D.ts (hunk 2 above)
Comment (jiawulin001) [reply src/coord/cartesian/Cartesian2D.ts]: Thank you for pointing this out! Zrender does have some handful functions I ignored.

File: src/component/marker/MarkAreaView.ts (hunk 3 above)
Comment (pissang) [reply src/component/marker/MarkAreaView.ts]: Got it. Thanks for the detailed explanation. Perhaps we can tweak the description a bit to make it more clear. For example:

Returning true directly may also do the work. But filtering ahead will avoid creating too much unnecessary elements when there are huge amount of elements.

**Comment by pissang** [comment]
Added recorded user interaction for visual regression testing

File: src/component/marker/MarkAreaView.ts (hunk 3 above)
Comment (jiawulin001) [reply src/component/marker/MarkAreaView.ts]: Good point. Comment updated.

**Review by pissang — DISMISSED** [review]

File: src/component/marker/MarkAreaView.ts [hunk 4]
```diff
@@ -123,6 +123,22 @@ function markAreaFilter(coordSys: CoordinateSystem, item: MarkAreaMergedItemOpti
         ) {
             return true;
         }
+        //Directly returning true may also do the work,
+        //because markArea will not be shown automatically
+        //when it's not included in coordinate system.
+        //But filtering ahead can avoid keeping rendering markArea
+        //when there are too many of them.
+        return markerHelper.zoneFilter(coordSys, {
```
Comment (pissang) [inline src/component/marker/MarkAreaView.ts:131]: Another suggestion. There are two places creating same object
```ts
{
    coord: fromCoord,
    x: item.x0,
    y: item.y0
 }
```

We can assign it to a temporary variable ahead to avoid redundant codes.

```ts
const item1 = { coord, x, y }
const item2 = { coord, x, y }
```

Comment (jiawulin001) [reply src/component/marker/MarkAreaView.ts]: Right, now it looks neater.

**Review by pissang — APPROVED** [review]
