### PR TITLE
fix(axis): only `value` has `scale` in cartesian

### LINKED ISSUE #10174: log yAxis with scale
### Version
4.2.1

### Reproduction link
[https://jsfiddle.net/tmtron/nwqer03u/](https://jsfiddle.net/tmtron/nwqer03u/)

### Steps to reproduce
use a yAxis with type 'log' and set scale to false

### What is expected?
it should be the same as not setting scale, since the doc says, that the default for scale=false

https://ecomfe.github.io/echarts-doc/public/en/option.html#yAxis.scale

### What is actually happening?
no scale at all and scale=false are NOT the same

---
I'd like to know what the yAxis is actually doing when we set scale=true: is it maybe just a bug, with the calculation of min/max?

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

According to [doc](https://echarts.apache.org/en/option.html#yAxis.scale)
In `catersain`, only `value` axis can have `scale`.

### Fixed issues

- Close #10174

### Before: What was the problem?

Screen Shot 2021-11-02 at 11 19 24 PM

### After: How is it fixed in this PR?

Screen Shot 2021-11-02 at 11 19 13 PM

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [x] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/coord/cartesian/AxisModel.ts [hunk 1]
```diff
@@ -57,6 +57,16 @@ export class CartesianAxisModel extends ComponentModel<CartesianAxisOption>
...
     }
+
+    getNeedCrossZero(): boolean {
+        const option = this.option;
+
+        if (option.type === 'value') {
+            return !option.scale;
+        }
+
+        return !axisDefault[option.type].scale;
```
Comment (pissang) [inline src/coord/cartesian/AxisModel.ts:68]: Seems it means the option provided to developers shows it can be configurable. But actually it doesn't. 

I think it's better to remove `scale` type definition and default values in `log`, `time`, `category` axis. And check if scale is `'interval'` in https://github.com/apache/echarts/blob/master/src/coord/scaleRawExtentInfo.ts#L99

Comment (pissang) [inline src/coord/cartesian/AxisModel.ts:68]: I'm not quite understand logic about this line.

Comment (pissang) [inline src/coord/cartesian/AxisModel.ts:68]: I'm not quite understand logic about this line.

File: src/coord/axisCommonTypes.ts [hunk 2]
```diff
@@ -111,7 +111,7 @@ interface NumericAxisBaseOptionCommon extends AxisBaseOptionCommon {
     maxInterval?: number;
 }
 
-export interface CategoryAxisBaseOption extends AxisBaseOptionCommon {
+export interface CategoryAxisBaseOption extends Omit<AxisBaseOptionCommon, 'scale'> {
```
Comment (pissang) [inline src/coord/axisCommonTypes.ts:114]: Just remove the `scale` property in `AxisBaseOptionCommon`

**Review by pissang — CHANGES_REQUESTED** [review]

**Review by pissang — APPROVED** [review]
