### PR TITLE
fix #17633: add gauge sectors in the order of the "clockwise" option

### LINKED ISSUE #17633: [Bug] 仪表盘顺时针和轴线展示的不一致
### Version

5.3.3

### Link to Minimal Reproduction

_No response_

### Steps to Reproduce

1.create gauge
2.option --> 
```js
option = {
  tooltip: {
    formatter: '{a} <br/>{b} : {c}%'
  },
  series: [
    {
      name: 'Pressure',
      type: 'gauge',
      clockwise: true,
      detail: {
        valueAnimation: true,
        formatter: '{value}'
      },
      data: [
        {
          value: 50,
          name: 'SCORE'
        }
      ],
      axisLine:{"roundCap":true,"lineStyle":{"width":16,"color":[[0.3,"#C9781B"],[0.7,"#F163EA"],[1,"#6366F1"]]}}
    }
  ]
};
```
3.result ->image

### Current Behavior

仪表盘开启clockwise：true， 同时开启axisLine的roundCap 和 分段颜色， 圆角不是顺时针展示的

### Expected Behavior

顺时针展示圆角

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by ZeekoZhu**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

add gauge sectors in the order of the "clockwise" option

### Fixed issues

#17633 

### Before: What was the problem?

image

The gauge view adds sectors in the order of the `colorList` option,  however, these elements will be covered by elements added later, and the order of the sectors looks reversed when the `roundCap` option is enabled.

### After: How does it behave after the fixing?

Reverse the sectors array before adding them to the graphic group

image

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

[gauge-case](https://github.com/ZeekoZhu/echarts/blob/86bbd4d8dd0b828cd91aa45584df53808d41e0db/test/gauge-case.html)

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/chart/gauge/GaugeView.ts [hunk 1]
```diff
@@ -154,11 +155,14 @@ class GaugeView extends ChartView {
...
             ));
 
-            group.add(sector);
+            sectors.push(sector);
 
             prevEndAngle = endAngle;
         }
 
+        sectors.reverse();
+        sectors.forEach(sector => group.add(sector));
```
Comment (Ovilia) [inline src/chart/gauge/GaugeView.ts:164]: Please use `each` from `'zrender/src/core/util'` instead of `forEach`.

**Review by Ovilia — CHANGES_REQUESTED** [review]
Thanks for your contribution! It looks good to me except one small detail.

**Review by Ovilia — APPROVED** [review]
