### PR TITLE
fix(tooltip): fix potential NPE when setting option with `notMerge` strategy

### LINKED ISSUE #20335: [Bug] Cannot read properties of null (reading 'offsetWidth') when using notMerge
### Version

5.5.1

### Link to Minimal Reproduction

https://jsfiddle.net/az4p58gs/

### Steps to Reproduce

All you need to do once opening to reproduce the bug is to scroll around and zoom in/out until the crash occurs.

### Current Behavior

Currently, there is a chance that when scrolling for a crash to occur as shown below.
echarts-null-value

Below is the error message
```
echarts.min.js:45 Uncaught TypeError: Cannot read properties of null (reading 'offsetWidth')
    at t.getSize (echarts.min.js:45:781248)
    at e._updatePosition (echarts.min.js:45:792803)
    at e.<anonymous> (echarts.min.js:45:790188)
    at e._showOrMove (echarts.min.js:45:788953)
    at e._showAxisTooltip (echarts.min.js:45:790116)
    at e._tryShow (echarts.min.js:45:788458)
    at e.manuallyShowTip (echarts.min.js:45:787122)
    at echarts.min.js:45:786112
```

### Expected Behavior

The intended behaviour is:

1. rebuild options from scratch using new data
2. remember the previous scroll position
3. not crash when scrolling/zooming

In my real app, I achieve the first 2 points by taking the values from **chart.getOption** and manually merging them into the new object.

### Environment

_No response_

### Any additional comments?

In my real app, I've seen the issue even if the chart is rebuilt every 5 seconds instead of 100ms. As it seems to happen whenever **chart.setOption**, the interval was lowered to make it quicker to reproduce.

Although options does not change. In the real app, options could be built from the same data, but filtered to exclude certain data points.

### PR DESCRIPTION
**Pull request by ktx-abhay**
- Fix #20335 
- Optional chaining for tooltip `offsetWidth` and `offsetHeight`

## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [x] Please squash the commits into a single one when merging.

### CODE REVIEW

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 1]
```diff
@@ -461,15 +461,15 @@ class TooltipHTMLContent {
 
     getSize() {
         const el = this.el;
-        return [el.offsetWidth, el.offsetHeight];
+        return [el?.offsetWidth, el?.offsetHeight];
```
Comment (Ovilia) [inline src/component/tooltip/TooltipHTMLContent.ts:464]: We try to avoid `?.` in ECharts. Write explictly the expected value when `el` is not defined. Should it be something like `el ? [el.offsetWidth, el.offsetHeight] : [0, 0]` or what?

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 2]
```diff
@@ -461,15 +461,15 @@ class TooltipHTMLContent {
...
     }
 
     moveTo(zrX: number, zrY: number) {
         const styleCoord = this._styleCoord;
         makeStyleCoord(styleCoord, this._zr, this._container, zrX, zrY);
 
         if (styleCoord[0] != null && styleCoord[1] != null) {
-            const style = this.el.style;
+            const style: any = this.el?.style || {};
```
Comment (Ovilia) [inline src/component/tooltip/TooltipHTMLContent.ts:472]: `this.el ? (this.el.style || {}) : {}`

**Review by Ovilia — CHANGES_REQUESTED** [review]

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 1 above)
Comment (ktx-abhay) [reply src/component/tooltip/TooltipHTMLContent.ts]: I updated.

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 2 above)
Comment (ktx-abhay) [reply src/component/tooltip/TooltipHTMLContent.ts]: updated

**Review by Ovilia — DISMISSED** [review]

**Review by Ovilia — DISMISSED** [review]

**Comment by Ovilia** [comment]
We sincerely appreciate your valuable contributions! We are currently running a special promotion for users who submit a Pull Request between September 25, 2024, and December 31, 2024. Eligible participants will receive a two-year enterprise membership to Baidu Comate (**Please note that in order to register Comate, you need to have a phone number in China due to local regulations**), valued at 2000 RMB (approximately 285 USD).

To learn more about this product, please visit https://comate.baidu.com/. If you are interested in this offer, kindly send an email with the link to your Pull Request along with your Comate username and email address to ovilia@apache.org to claim your membership.

Thank you once again for your support!

File: src/component/tooltip/TooltipHTMLContent.ts [hunk 3]
```diff
@@ -461,15 +461,15 @@ class TooltipHTMLContent {
...
+        return el ? [el.offsetWidth, el.offsetHeight] : [0, 0];
     }
 
     moveTo(zrX: number, zrY: number) {
         const styleCoord = this._styleCoord;
         makeStyleCoord(styleCoord, this._zr, this._container, zrX, zrY);
 
         if (styleCoord[0] != null && styleCoord[1] != null) {
-            const style = this.el.style;
+            const style: any = this.el ? (this.el.style || {}) : {};
```
Comment (plainheart) [inline src/component/tooltip/TooltipHTMLContent.ts:472]: Falling `el.style` back to `{}` makes no sense. It just circumvents those errors and causes unnecessary invoking. I would suggest:

```js
moveTo(zrX: number, zrY: number) {
  if (!this.el) {
    return;
  }
  // ...
}
```

**Review by plainheart — CHANGES_REQUESTED** [review]

File: src/component/tooltip/TooltipHTMLContent.ts (hunk 1 above)
Comment (plainheart) [reply src/component/tooltip/TooltipHTMLContent.ts]: Another reason is that ECharts will be eventually transpiled to ES3, and the optional chaining operator `?.` will be polyfilled to:
```js
return [el === null || el === void 0 ? void 0 : el.offsetWidth, el === null || el === void 0 ? void 0 : el.offsetHeight];
```
It causes an unexpected increment in code size, which ECharts tries to avoid until we target ECharts to ES2020.

**Review by plainheart — APPROVED** [review]
