### PR TITLE
Fix(brush): clamp range when brush

### LINKED ISSUE #14416: Unexpect bar count when use zoomSelect
### Version
4.9.0

### Reproduction link
[https://stackblitz.com/edit/js-xpyfvk?file=index.js](https://stackblitz.com/edit/js-xpyfvk?file=index.js)

### Steps to reproduce
when the right edge of the selected range hit the chart's right edge, the bar count is not match my selection.
chrome-capture (1)

### What is expected?
bar count should match my selection.

### What is actually happening?
there is one extra bar.

---
I need to display a table below the bar chart. And the rows of table is the same as the bar count.
I use zoom event params to calculate the rows.
But when selection hit the edge, the row count calculated from event params is one less then the chart.

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

It should clamp range when brush, otherwise, range would larger than 1, because brushed area might exceed the last item.

### Fixed issues

Close #14416 

### Before: What was the problem?

Kapture 2021-03-31 at 17 35 49

### After: How is it fixed in this PR?
Kapture 2021-03-31 at 17 37 21

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs
`brush3.html`

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/coord/cartesian/Cartesian2D.ts [hunk 1]
```diff
@@ -146,15 +146,15 @@ class Cartesian2D extends Cartesian<Axis2D> implements CoordinateSystem {
         return out;
     }
 
-    pointToData(point: number[], out?: number[]): number[] {
+    pointToData(point: number[], out?: number[], reserved?: number[], clamp?: boolean): number[] {
```
Comment (pissang) [inline src/coord/cartesian/Cartesian2D.ts:149]: This `reserved` parameter in the base class is preserved for parameters like `clamp`. So there is no need to add another clamp parameter.  Also, the order is wrong. It should be `pointToData(point, clamp, out)`;

There are two other changes I think we can do to simplify the design after searched the code.
1. Remove the `out` parameter because I found there are no lines of code use it.
2. Replace the `reserved?: any` parameter with a `clamp?: boolean` parameter because I didn't see any other possibilities. Correct me if I'm wrong

File: src/component/helper/BrushTargetManager.ts [hunk 2]
```diff
@@ -422,26 +423,30 @@ const coordConvert: Record<BrushType, ConvertCoord> = {
...
         xyMinMax: BrushDimensionMinMax[]
     } {
-        const xminymin = coordSys[COORD_CONVERTS[to]]([rangeOrCoordRange[0][0], rangeOrCoordRange[1][0]]);
-        const xmaxymax = coordSys[COORD_CONVERTS[to]]([rangeOrCoordRange[0][1], rangeOrCoordRange[1][1]]);
+        const xminymin = to
+            ? coordSys.pointToData([rangeOrCoordRange[0][0], rangeOrCoordRange[1][0]], [], [], clamp)
+            : coordSys.dataToPoint([rangeOrCoordRange[0][0], rangeOrCoordRange[1][0]]);
+        const xmaxymax = to
+            ? coordSys.pointToData([rangeOrCoordRange[0][1], rangeOrCoordRange[1][1]], [], [], clamp)
+            : coordSys.dataToPoint([rangeOrCoordRange[0][1], rangeOrCoordRange[1][1]]);
```
Comment (pissang) [inline src/component/helper/BrushTargetManager.ts:435]: I think `dataToPoint` also can be clamped?

**Review by pissang — CHANGES_REQUESTED** [review]

File: src/coord/cartesian/Cartesian2D.ts (hunk 1 above)
Comment (susiwen8) [reply src/coord/cartesian/Cartesian2D.ts:149]: @pissang But, in base class [`CoordinateSystem`](https://github.com/apache/echarts/blob/master/src/coord/CoordinateSystem.ts#L133), the params for `pointToData` are ` point: number[],  reserved?: any, out?: number[]`, I have tried rearrange to ` point: number[],  out?: number[], reserved?: any`, but that would break type.

**Review by pissang — APPROVED** [review]

**Comment by pissang** [comment]
Found some exists very old bad designs durging the review. Going to fix it in a separate PR
