### PR TITLE
fix(visualMap): use itemSymbol as default symbol type and fix #5719

### LINKED ISSUE #5719: itemSymbol in the visualMap (piecewise) can't be set
Version: 3.5.4

Seems like itemSymbol can't be changed to "circle" or other values in visualMap: 

image

### PR DESCRIPTION
**Pull request by Ovilia**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

`visualMap[piecewise].itemSymbol` took no effect.

### Fixed issues

- #5719: itemSymbol in the visualMap (piecewise) can't be set

### Before: What was the problem?

`visualMap[piecewise].itemSymbol` took no effect.

### After: How is it fixed in this PR?

`visualMap[piecewise].itemSymbol` should be used as default symbol type when `symbol` is not defined in visualMap pieces.

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

- `test/visualMap-scatter-colorAndSymbol.html`

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/component/visualMap/VisualMapModel.ts [hunk 1]
```diff
@@ -511,7 +516,7 @@ class VisualMapModel<Opts extends VisualMapOption = VisualMapOption> extends Com
 
                 // Filter square and none.
                 visuals.symbol = mapVisual(visuals.symbol, function (symbol) {
-                    return (symbol === 'none' || symbol === 'square') ? 'roundRect' : symbol;
+                    return (symbol === 'none' || symbol === 'square') ? defaultSymbol : symbol;
```
Comment (pissang) [inline src/component/visualMap/VisualMapModel.ts:519]: @100pah Do you still remember why the `'square'` symbol needs to be filtered?

**Review by pissang — APPROVED** [review]

**Review by pissang — APPROVED** [review]
