### PR TITLE
fix(labelLine): update labelLine `ignore`

### LINKED ISSUE #16539: [Bug] LabelLine doesn't hide
### Version

5.3.0

### Link to Minimal Reproduction

https://codesandbox.io/s/practical-joliot-vt6glv?file=/src/components/Echarts.vue

### Steps to Reproduce

1、Set option normally
```
      const option = {
        series: [
          {
            name: "Access From",
            type: "pie",
            radius: "50%",
            data: [
              { value: 1048, name: "Search Engine" },
              { value: 735, name: "Direct" },
              { value: 580, name: "Email" },
              { value: 484, name: "Union Ads" },
              { value: 300, name: "Video Ads" },
            ],
          },
        ],
      };
      this.myChart.setOption(option);
```
2、Set labelLine to hide
```
      setTimeout(() => {
        const option = {
          series: [
            {
              name: "Access From",
              type: "pie",
              radius: "50%",
              data: [
                { value: 1048, name: "Search Engine" },
                { value: 735, name: "Direct" },
                { value: 580, name: "Email" },
                { value: 484, name: "Union Ads" },
                { value: 300, name: "Video Ads" },
              ],
              labelLine: {
                show: false,
              },
              emphasis: {
                labelLine: {
                  show: false,
                },
              },
            },
          ],
        };
        this.myChart.setOption(option);
      }, 5000);
```

### Current Behavior

LabelLine is not hidden when emphasis

### Expected Behavior

LabelLine is hidden when emphasis

### Environment

```markdown
- OS: Windows 10
- Browser:Chrome 98
- Framework: Vue@2
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

It should update `ignore`

### Fixed issues

- Close #16539 

### Before: What was the problem?

Kapture 2022-02-19 at 00 11 55

### After: How is it fixed in this PR?

Kapture 2022-02-19 at 00 09 51

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

pie-label.html

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Comment by pissang** [comment]
Sorry for the late review.

The `ignore` property of `label` and `labelLine` is updated in 
https://github.com/apache/echarts/blob/ad3a07a4bc699f540d2c977160cfc466fa77793b/src/label/labelStyle.ts#L250
https://github.com/apache/echarts/blob/ad3a07a4bc699f540d2c977160cfc466fa77793b/src/label/labelGuideHelper.ts#L623

Especially the `labelLine`, it has complex logic to determine if it can be shown when label is not shown. But for some reason it fails when switching from show to hide in the emphasis state.

**Comment by susiwen8** [comment]
@pissang Thanks for the pointer

File: src/chart/pie/PieView.ts [hunk 1]
```diff
@@ -58,6 +58,7 @@ class PiePiece extends graphic.Sector {
         const seriesModel = data.hostModel as PieSeriesModel;
         const itemModel = data.getItemModel<PieDataItemOption>(idx);
         const emphasisModel = itemModel.getModel('emphasis');
+        const selectModel = itemModel.getModel('select');
```
Comment (pissang) [inline src/chart/pie/PieView.ts:61]: This line can be removed

Comment (susiwen8) [reply src/chart/pie/PieView.ts]: done
